### ISSUE TITLE
Add support for SPDX JSON and YAML files

### ISSUE THREAD

**Issue by sschuberth** [DependencyTrack/dependency-track#1007]
### Current Behavior:

Only SPDX RDF and Tag / Value formats are supported.

### Proposed Behavior:

Additionally support JSON and YAML formats for import of SPDX files.

**Comment by sschuberth** [comment]
Probably the [new SPDX Java library](https://github.com/spdx/Spdx-Java-Library) comes in handy for implementation.

**Comment by stevespringett** [comment]
Yes, I do have plans to remove the old SPDX Tools library and replace it with the new library. As of now, it hasn't been a priority since a very small percentage of DT adopters use SPDX with it (likely < 5%).

Looking at the backlog, it looks like v4.5 would be the earliest I could include this, so I'm targeting that release for the time being.

**Comment by stevespringett** [comment]
Closing as support for SPDX file formats were removed in #1053
