### ISSUE TITLE
Dependency-track does not send emails when a component is vulnerable.

### ISSUE THREAD

**Issue by meto1111** [DependencyTrack/dependency-track#1051]
Sending configuration emails works properly but when I create an alert and want to test this, I don't receive an email about the vulnerable component. Any ideas how i can configure this?

**Comment by stevespringett** [comment]
Did you specify the group information so that DT knows on what type of conditions to send notifications for?
https://docs.dependencytrack.org/integrations/notifications/

**Comment by meto1111** [comment]
Hi Steve,

Yes I specify the group information to NEW_VULNERABILITY and NEW_VULNERABLE_DEPENDENCY

**Comment by meto1111** [comment]
Do you have an idea what might be blocking emails from coming through?

**Comment by nscuro** [comment]
I'm seeing this behavior as well, but with WebHooks. Turns out notifications aren't sent when analysis results (e.g. from OSS Index) are applied from cache. So @meto1111 if the components in your test BOMs have been analyzed in the last 3 days, you won't get a notification.

@stevespringett I didn't use notifications until now so I haven't noticed that earlier. Seems like this is a regression since the new component model is in place? Was sending of notificiations here intentionally left out?

https://github.com/DependencyTrack/dependency-track/blob/master/src/main/java/org/dependencytrack/tasks/scanners/BaseComponentAnalyzerTask.java#L157 

vs. 

https://github.com/DependencyTrack/dependency-track/blob/master/src/main/java/org/dependencytrack/tasks/scanners/OssIndexAnalysisTask.java#L250-L251
