### ISSUE TITLE
OIDC: Introduce stable and static absolute reply-url

### ISSUE THREAD

**Issue by cmenzi** [DependencyTrack/dependency-track#1107]
### Current Behavior:

Currently, there is the need to add `*` to the reply-url, which is not allowed in Azure AD:

- https://docs.microsoft.com/en-us/azure/active-directory/develop/reply-url#restrictions-on-wildcards-in-redirect-uris

Microsoft at their side, referring to https://datatracker.ietf.org/doc/html/rfc6749#section-3.1.2, where it's also stated.

### Proposed Behavior:

Change the reply-url to absolute stable url without fragements, ..., in order to fulfill recommended best practices.

**Comment by nscuro** [comment]
RFC6749 states:

> The redirection endpoint URI MUST be an absolute URI as defined by [RFC3986] Section 4.3.  
> The endpoint URI MAY include an "application/x-www-form-urlencoded" formatted (per Appendix B) query
> component ([RFC3986] Section 3.4), which MUST be retained when adding additional query parameters.  
> The endpoint URI MUST NOT include a fragment component.

To my understanding, the following URIs are valid according to the RFC:

* `https://dependencytrack.example.com/static/oidc-callback.html`
* `https://dependencytrack.example.com/static/oidc-callback.html?foo=bar`

Invalid URIs would be:

* `static/oidc-callback.html`
* `https://*.example.com/static/oidc-callback.html`
* `https://dependencytrack.example.com/static/oidc-callback.html#foo=bar`

Does it work without the wildcard character, e.g. with  `https://dependencytrack.example.com/static/oidc-callback.html`? I can't test with AzureAD, but maybe query parameters don't have to be included in the redirect URI. In Keycloak they have to be, which is why it's mentioned in the docs.

**Comment by cmenzi** [comment]
Yes. It works with query parameters. The issue is that then every page (?redirect=dashboard, ...) needs to added as reply url to the azure app.

Usually, if you open for example the projects page and you are not authenticated, the page is added as query param the oidc-callback.html.

**Comment by daniel-anova** [comment]
Will this enhancement be considered? Currently need to deploy a keycloak instance to act as middleware so I can use AzureAD OpenID.

**Comment by nscuro** [comment]
@cmenzi @daniel-anova This should be fixed in https://github.com/DependencyTrack/frontend/pull/113

**Comment by cmenzi** [comment]
@nscuro Cool and many thanks! Waiting for the release!

**Comment by daniel-anova** [comment]
@nscuro That's great news, any set date for the new release? Would greatly simplify our deployment if we could have this.

**Comment by stevespringett** [comment]
I'm trying to get DT 4.4 released by mid-February. NPM Advisory mirroring will cease to work on February 16.

https://github.blog/changelog/2021-11-16-deprecating-non-audit-related-advisory-fetch-endpoints-for-the-npmjs-com-registry-api/

**Comment by valentijnscholten** [comment]
> Currently, there is the need to add `*` to the reply-url, which is not allowed in Azure AD:

I can confirm this is no longer needed, tested with v4.4.1 (and Azure AD)

**Comment by nscuro** [comment]
This was shipped with 4.4.
