### ISSUE TITLE
No "Used by" and "Projects" view for components in version 4.0

### ISSUE THREAD

**Issue by jagusztinl** [DependencyTrack/dependency-track#1119]
The enhancement may already be reported! Please search for the enhancement before creating one.

### Current Behavior:
No "Used by" and "Projects" view for components in version 4.0

### Proposed Behavior:
Please put it back as we had it in version 3.8

Examples:
<img width="379" alt="missing_projects" src="https://user-images.githubusercontent.com/46651189/127040798-6a4eb548-550b-4e2b-8a3a-396545d31817.png">
<img width="325" alt="projects_3 8" src="https://user-images.githubusercontent.com/46651189/127040816-1c2f82ad-0870-498c-8c1f-78913dd663b8.png">
<img width="740" alt="usedby_3 8" src="https://user-images.githubusercontent.com/46651189/127040826-560a33aa-1915-4f7d-a005-4b311e376247.png">

**Comment by stevespringett** [comment]
Please propose a way to do this.

v3.8 and prior was broken by design. It had a centralized component model that neglected the reality of malicious components, modified component, component provenance, hashes, etc.

The version of Ant 1.6.5 in the screenshot does not provide enough information for me to know if that specific component is used anywhere else. The screenshot of FastInfoSet 1.2.13 made a ton of assumptions that will lead to erroneous results.

Please provide use cases and proposals for how to achieve this that will not negatively impact database performance.

**Comment by jagusztinl** [comment]
We are looking for that functionality, that helps us to tracks component usage in our projects.

We need a GUI that lists all identified components in the database (like https://user-images.githubusercontent.com/46651189/127040826-560a33aa-1915-4f7d-a005-4b311e376247.png was) and we are able to trace back where/in what projects these components used (like https://user-images.githubusercontent.com/46651189/127040816-1c2f82ad-0870-498c-8c1f-78913dd663b8.png was).

Dependency Track data modell have an exact list of components (e.g. sw libraries) and projects so it should be easily implemented.

**Comment by stevespringett** [comment]
> so it should be easily implemented

Not exactly. The query would need to incorporate:
* identity ( [group, name, version], purl, cwe, swidTagId)
* hash (exact match on all possible hash algorithms and values)
* provenance (ensure the components were retrieved from the same place)
* Ensure the components have the same assemblies (subcomponents) (if any)
* If the component was digitally signed, that may also be a consideration

I'm sure there's other criteria that would be necessary in order to determine if the exact component is used in other projects or not. Another issue that compounds the problem is if Ant 1.6.5 has a hash value in one project but not in the other project, it will not be possible to determine if the specific version of Ant 1.6.5 is used elsewhere or not because the BOMs uploaded to the other project could potentially have incomplete data.

> Without this functionality the essential dependency tracking functionality missing from the system.

Using the component search capability, you can already search based on identify or hash across all projects to determine where that identify or hash is used. It's just not as convenient as "Used By" functionality in <=3.8. However, IMO, the new component search capabilities are much more powerful than what was previously available.

--- 
A compromise to the two approaches would be to support both exact and partial matches. So if a projects (used by) tab did exist, it could potentially list out all the components that have some sort of match with a column indicating an exact match or not. This would be ideal, but would kill performance, so these calculations would need to be performed in advance and stored somewhere - possibly in Lucene. But it's certainly a non-trivial enhancement.

**Comment by jagusztinl** [comment]
Thanks a lot for your detailed explanation, now I see it.

**Comment by msymons** [comment]
Does this have to be closed?  It might not be implemented any time soon, and it might not be easy to implement...  but the idea of "partial matches" does sound useful.
