### ISSUE TITLE
Go Versions Are Not Comparable

### ISSUE THREAD

**Issue by officerNordberg** [DependencyTrack/dependency-track#1574]
### Current Behavior:
Using Docker cyclonedx/cyclonedx-gomod my bom.json _correctly_ gets generated with components containing versions and purls prefixed with the letter 'v'.
[Go Versioning](https://go.dev/doc/modules/version-numbers)
[Semantic Versioning for Git](https://semver.org/#is-v123-a-semantic-version)

### Steps to Reproduce:
Upload bom containing component 
```
    {
      "name" : "github.com/tidwall/gjson",
      "version" : "v1.6.0",
      "purl" : "pkg:golang/github.com/tidwall/gjson@v1.6.0?type=module",
      "type" : "library",
    }
```

### Expected Behavior:
This component should have multiple vulnerabilities but none are found. Manually removing the 'v' results in expected matching.
Match: 
CVE-2020-35380
CVE-2020-36066
CVE-2020-36067
CVE-2021-42836

### Environment:
  
  - Dependency-Track Version: 4.4.2
  - Distribution: Docker & Executable WAR
  - BOM Format & Version: json 1.4
  - Database Server:  H2 & PostgreSQL 
  - Browser: 

### Additional Details:
I'd suggest either excluding 'v' from the capture group
https://github.com/DependencyTrack/dependency-track/blob/3b517fedee203ecbfbb812eadb8045f969aceddb/src/main/java/org/dependencytrack/util/ComponentVersion.java#L92
or checking for prefix prior to parseInt
https://github.com/DependencyTrack/dependency-track/blob/3b517fedee203ecbfbb812eadb8045f969aceddb/src/main/java/org/dependencytrack/util/ComponentVersion.java#L264

**Comment by nscuro** [comment]
> Manually removing the 'v' results in expected matching.

I fear I can't reproduce this. It looks like the internal analyzer fails to find any `VULNERABLESOFTWARE` entries for that package. That particular query does not include any versions.

When searching the DB for the component in question, I get this:

```sql
SELECT "PURL_NAMESPACE", "PURL_NAME" FROM "VULNERABLESOFTWARE" WHERE "PURL_NAME" LIKE '%gjson%'
```

| PURL\_NAMESPACE | PURL\_NAME |
| :--- | :--- |
| NULL | github.com/tidwall/gjson |
| NULL | github.com/tidwall/gjson |
| NULL | github.com/tidwall/gjson |

Note how the namespace is empty. This is kinda correct for Go, because `github.com/tidwall/gjson` *is* the package name.  However, at runtime, the PURL of the component being analyzed looks like this:

<img width="591" alt="image" src="https://user-images.githubusercontent.com/5693141/166159806-cb839d84-6fe0-4a3b-af6b-26a519994b4e.png">

Should be fixable by adjusting how PURLs are generated for GHSA vulnerabilities. Maven and NPM do get a special treatment here already: https://github.com/DependencyTrack/dependency-track/blob/494268ec0c12b66b30e3f01b739c5fa387dec546/src/main/java/org/dependencytrack/tasks/GitHubAdvisoryMirrorTask.java#L285-L290

This may mean that we need to `DROP` all `VULNERABLESOFTWARE` rows that are affected by this during the v4.5.0 upgrade.

**Comment by nscuro** [comment]
Should be fixed in #1580:

<img width="1218" alt="image" src="https://user-images.githubusercontent.com/5693141/166523791-a97158fa-8c9d-4612-ab73-388392dd8dae.png">

CVE-2020-36067 still won't be detected as it's missing in OSS Index and GHSA. And because the component has no CPE, matching against NVD is not possible.

**Comment by officerNordberg** [comment]
As you can imagine, I'm not satisfied with this answer. OSS Index is garbage from everything I've seen, I've disabled it because at best it adds duplicates but lacks so much information as to be mostly false negatives. I've been actively working on adding fuzzy matching to DT to build CPEs with wildcards like NVD uses to handle cases like this whether the project adopts it or not.  I just don't see why DT shouldn't demonstrate it can match all vulns if I'm to trust it to report on new ones.  I'm often comparing my results against a partner's internally developed project but we need our own solution and the baseline should be it reports on ~100% of the known vulns today. Not ~90%.  </rant>  How are others validating DT's results? 
https://nvd.nist.gov/products/cpe/search/results?namingFormat=2.3&keyword=cpe%3A2.3%3Aa%3A*%3Agjson%3A1.6.0%3A*%3A*%3A*%3A*%3A*%3A*%3A*

**Comment by officerNordberg** [comment]
@nscuro Thanks for the effort and follow-up.
