### ISSUE TITLE
Add the possibility to manage users via LDAP.

### ISSUE THREAD

**Issue by Mazorius** [DependencyTrack/dependency-track#187]
### Issue Type:
  - [ ] defect report
  - [x] enhancement request
  
  
### Current Behavior:
Currently, a user must be added manually and the authorization and group membership must be set via LDAP before logging in.

### Steps to Reproduce (if defect):
-

### Expected Behavior:
I define in the properties which LDAP groups (nested should be possible) are assigned to which team.
If the team does not exist at this time, it is added with a specific list of permissions that the team member inherits.

### Environment:
  
  - Dependency-Track Version: 3.1.1
  - Distribution: Executable WAR
  - BoM Format & Version:
  - Database Server: PostgreSQL
  - Browser: Safari, Chrome

### Other Details:
The AWX LDAP implementation can serve as an example.

**Comment by stevespringett** [comment]
@Mazorius A few questions and clarifications...

If a team is mapped to an LDAP group and a user who is in one of the mapped groups logs into Dependency-Track for the first time, they will be assigned to that team and inherit the teams permissions. That's my understanding and I think its doable. 

Question... If the user is then removed from the LDAP group, is the expected behavior to also remove the user from the team membership in Dependency-Track? So more of a synchronization between LDAP and DT regarding DN's and their groupmembership? If so, this should't be a big deal as there's already some LDAP synchronization that occurs today, but would need to be enhanced to include groupmembership and possibly some other attributes.

Also my understanding that a team will have a N-M relationship with LDAP groups. So a single team can be mapped to zero or more groups in LDAP. If a user is a member of multiple LDAP groups mapped to different teams with different permissions, an aggregate of all inherited team permissions shall become the users effective permissions. Is that the expected behavior?

You mentioned:
> The AWX LDAP implementation can serve as an example.

What does this refer to?

Also, I'm going to try to incorporate this into v3.3.

**Comment by stevespringett** [comment]
Great! Thanks for the clarification.

**Comment by stevespringett** [comment]
Are you using Active Directory? If not, which LDAP implementation does your org use?

For nested groups, Active Directory has a very specific way to perform the query that doesn't require recursion. Its unclear if other implementations have a way to do this. There's nothing in the spec that would work across all implementations. The logic would likely be:

```java
if (activeDirectory) {
  // perform efficient nested group query
} else if (config.isRecursionEnabled) {
  // perform recursion (will likely upset IT)
} else {
  // direct group membership only
}
```

**Comment by Mazorius** [comment]
Hi @stevespringett 

we are using Active Directory with Nested Groups in our Company.

PS: I see that know the xml parsing works better in 3.2.1 … thanks for that (If you made some changes 👍  )

**Comment by stevespringett** [comment]
The following configuration options (in application.properties) are used to configure this behavior.

```ini
# Optional
# Specifies if Alpine (ldap user) accounts are automatically created upon successful authentication.
# When a user logs in with valid credentials but an account has not been previously provisioned
# (either manually or via enabling this option), an authentication failure will be returned. This
# allows admins to control specifically which ldap users can access the system and which users
# cannot. When this value is set to true, an Alpine ldap user account will be created and mapped to
# the ldap account automatically. This automatic provisioning only affects authentication, not
# authorization.
alpine.ldap.user.provisioning=false

# Optional
# This option will ensure that Alpine LDAP user account team memberships are dynamic and synchronized
# with membership of LDAP groups. When an Alpine team is mapped to an LDAP group, all Alpine LDAP users
# will automatically be assigned to the team if they are a member of the group the team is mapped to.
# If the user is later removed from the LDAP group, they will also be removed from the team. This option
# provides the ability to dynamically control user permissions via an external directory server.
alpine.ldap.team.synchronization=false
```

For your use-case, I believe you'll need to set the value of these two properties to `true`.

At this point, all backend functionality is working for both of these options and should satisfy the request. Team <-> LDAP Group mapping in the user interface is the last remaining task.

**Comment by stevespringett** [comment]
No, not at all. Each team can be mapped to 0 or more LDAP groups. The system then determines mapping based on the groups DN within the directory. The name of the team in Dependency-Track is irrelevant and not used for mapping.

Now, if the DNs of the groups ever change in the directory, the mappings for the groups affected will be broken. But this rarely happens, but it's something to be aware of.

**Comment by stevespringett** [comment]
This functionality is complete and has been successfully tested against Active Directory, ApacheDS, Fedora 389 Directory, and eDirectory. Configuration examples have been written and will be published upon release. Please note that there's a few existing LDAP config options (in application.properties) that have been removed or slightly changed meaning. The domain option has been removed. The user format option and the bind username option has changed slightly. These will be documented in the release notes but I wanted you to be aware of them.

**Comment by Mazorius** [comment]
Many thanks ;)
