### ISSUE TITLE
Vulnerable component registered does not show vulnerabilities

### ISSUE THREAD

**Issue by amenezes** [DependencyTrack/dependency-track#190]
When a vulnerable component is registered the vulnerabilities its always zero.

### Issue Type:
  - [x] defect report
  - [ ] enhancement request
  
  
### Current Behavior:
When a vulnerable component is registered on dependency-track after an analysis its value is always zero.

### Steps to Reproduce (if defect):
Add Struts 2.3.5 component on dependency-track and select refresh button.

### Expected Behavior:
When a vulnerable component is registered after an analysis vulnerabilities, the vulnerabilities must be non-zero.

### Environment:
  
  - Dependency-Track Version: 3.1.1 | latest
  - Distribution: Docker
  - BoM Format & Version: -
  - Database Server: H2
  - Browser: opera / chrome

### Other Details:
I tried simulate this page: ![dependency-track example](https://docs.dependencytrack.org/images/screenshots/vulnerable-component.png)
CVE - Struts 2.3.5 vulnerabilities: https://www.cvedetails.com/vulnerability-list/vendor_id-45/product_id-6117/version_id-209271/Apache-Struts-2.3.5.html

Some screenshots from my local system/container environment: 
struts 2.3.5 component registered: ![struts](https://www.dropbox.com/s/6gwd843uoe68a8o/dependency-track01.png?raw=1)
cve present on dependency-track: ![cve](https://www.dropbox.com/s/o5d613cidvndwub/dependency-track-02.png?raw=1)

**Comment by stevespringett** [comment]
Cannot reproduce. What do the logs say?

**Comment by amenezes** [comment]
@stevespringett,

Follows the dependency-track.log file:
 - https://www.dropbox.com/s/90kn21wk0yyo2bw/dependency-track.log?dl=0

**Comment by stevespringett** [comment]
There are a lot of download errors and there are dependency-check exceptions (likely due to errors in the mirrored NVD data)

I'd recommend:
* Stop the server
* delete the ~/.dependency-track/nist directory
  * This forces a complete remirror of the NVD
* Start the server

You should have 2002 - 2018 download successfully without error. During this time, do not use the system. As stated in the docs, the system needs to seed completely before usage, which typically takes between 5-30 minutes. Monitor the logs to see when everything completes. Do not shut down the system during this time unless you encounter more download errors and need to fix them.

If you continue to get dependency-check exceptions, change the logging level from INFO to DEBUG for org.owasp.dependencycheck in logback.xml

**Comment by amenezes** [comment]
@stevespringett,

Sorry for the delay.

I'm made a copy of dependency-track and change [logback.xml](https://github.com/amenezes/dependency-track/blob/master/src/main/docker/logback.xml) file for generate a new docker image file, available here: [amenezes/dependency-track:snapshot](https://hub.docker.com/r/amenezes/dependency-track/).

I'm too made a new test on cloud provider, to discard problems with my Internet connection relative with the download of nvd files, but the result was the same. 

I used a machine template: 4 gb RAM | 2 vcpus. 

This time I generated the hash of nvd files downloaded, available here:
- [md5sum.txt](https://www.dropbox.com/s/1u2bxrbyg49kzly/md5sum.txt?raw=1)
- [sha1sum.txt](https://www.dropbox.com/s/kmw23gregjni1t3/sha1sum.txt?raw=1)
- [sha256sum.txt](https://www.dropbox.com/s/3b8k813kv4kkifp/sha256sum.txt?raw=1)

The new [dependency-track-log](https://www.dropbox.com/s/gv25vnqb86yfgsd/dependency-track.2.log?raw=1) file still have errors relative to _private.key_ and with the _Dependency-Check scan agent_.

Is there some more that can I try?

**Comment by stevespringett** [comment]
I was able to reproduce the issue with Dependency-Check update on a clean Docker install. The issue has been corrected with 97349e56b6497d6b63f7c1a6c75d9c968b20a911 and will be included in v3.2 being released later today.
