### ISSUE TITLE
LDAP - DN doesn't contain user name

### ISSUE THREAD

**Issue by csharpPrgmmr** [DependencyTrack/dependency-track#192]
### Issue Type:
  - Question, Enhancement request
  
  
### Current Behavior:
My organization's user DNs do not contain the user name, it starts with a unique identifier.  Given the current ldap settings the registration works correctly, but the authentication does not.  I notice the DN is stored.  I was able to do a local build that corrected the issue and leveraged the stored DN as opposed to trying to reconstruct it using the pattern available in the configuration.

### Environment:
  
  - Dependency-Track Version:
  - Distribution: [ Docker | Executable WAR | Traditional WAR ]
  - BoM Format & Version:
  - Database Server: [ H2 | MSSQL | MySQL | PostgreSQL ]
  - Browser: 

### Other Details:
I'm willing to contribute to the fix, but I wanted to get feedback about where / how to address it as the core of this code resides in the alpine auth code.

**Comment by stevespringett** [comment]
The DN is stored but never used. When you add an LDAP User to Dependency-Track, the system will 'sync'. This syncing action pulls in the users DN and stores it. It's not used anywhere in the code as of now, and it's certainly not used for authentication.

Alpine **can** build up a users pseudo DN for authentication but I'd highly advise against it. Most Active Directory users would simply use %s or %s@domain.com.

Also note, that Dependency-Track does not automatically create LDAP Users. You have to create them first, assign team membership and permissions, then they'll be able to login.

As is, Alpine is really flexible. I'd be surprised if it couldn't be configured to authenticate your users.

**Comment by csharpPrgmmr** [comment]
I am able to properly register the ldap users; however, the issue comes when any LDAP user tries to sign in.  If a typical user id is user123, the DN for that user is something like uniqueId=6789,ou=group,dc=domain,dc=com.  Any deviation from that during the sign in throws an ldap unavailable error (validated via ldp.exe).  The %s pattern doesn't help in this situation because the user name isn't actually part of the DN; however, it is available as a part of the ldap user object.

**Comment by stevespringett** [comment]
As stated before, the DN is irrelevant and not used. I went ahead and attempted to reproduce this issue but could not.

#### LDAP User Entry with UUID in the DN instead of username:
<img width="1792" alt="apache-directory-studio" src="https://user-images.githubusercontent.com/3878933/44416022-7c2e6600-a537-11e8-99ab-42f51f4ab3b8.png">

#### User Management (from v3.2):
![usermanagement](https://user-images.githubusercontent.com/3878933/44416130-b8fa5d00-a537-11e8-9499-b92ca56ec031.png)

#### The testaccount LDAP user logged in:
![ldapuser-logged-in](https://user-images.githubusercontent.com/3878933/44416188-df1ffd00-a537-11e8-9148-9631fff371de.png)

#### The application.properties to make it happen:
<img width="722" alt="application" src="https://user-images.githubusercontent.com/3878933/44416208-efd07300-a537-11e8-9c55-1b7568e96d83.png">

**Comment by csharpPrgmmr** [comment]
Ok, thanks for looking into it.  There may be something odd with our setup.  There is no userPrincipalName attribute setup and when I attempt to use something I know is there like uid or mail it fails on invalid credentials.  When I use the stored DN as the Principal/username it works fine.

**Comment by stevespringett** [comment]
Closing
