### ISSUE TITLE
Help me manually uploading D-Check XML into D-Track via API

### ISSUE THREAD

**Issue by Arunraj89** [DependencyTrack/dependency-track#194]
Team, 

Help me to upload D-Checker XML/HTML output file into D-Track via Rest API. 

I tried to do the same as it was told in "https://docs.dependencytrack.org/usage/cicd/" , I am not sure about the decaffeinate value for few parameters like SCAN and UUID. Where can i get those... 

curl -X "PUT" "http://localhost:8080/api/v1/scan" \
       -H 'Content-Type: application/json' \
       -H 'X-API-Key: v0oNAqW3FeouFI4mgzIMCPMY1VOSqpZX' \
       -d $'{
                  "project": "2621e83c-9315-4b40-8b94-65e251e46615",
                  "projectName": "AXA",
                  "projectVersion": "1.0",
                  "autoCreate": true, 
                 "scan": ""
              }' 'chrome-extension://localhost:8080/api/v1/scan'

Please help me with the sample, it will be great helpful. 

Thanks in advance.

**Comment by stevespringett** [comment]
The docs state what the value of `scan` must be. Here's one way you can get it.

On Linux, you can use:
`"scan": "$(cat path/to/dependency-check-report.xml |base64 -w 0 -)"`

On macOS, you can use:
`"scan": "$(cat path/to/dependency-check-report.xml |base64 -)"`

The UUID of the project can be obtained from the URL. Create a project, go into the project and copy the UUID from the URL.

The Dependency-Check Jenkins plugin does both of these things for you.

**Comment by razeitona** [comment]
Hi @stevespringett ,

I've uploaded a dependency-check xml file into Dependency-Track, worked almost perfectly. 
Only one vulnerability was recognized, the others I needed to go to each component and just press "Update" in "View Details" for Dependency-Track recognize is vulnerbility relation.

Didn't do to all because there's a lot of files. Do you know what can be? That only recognized NLog and others dependencies like Rebus.SqlServer, Sitecore and so I need to just press Update in ViewDetails

**Comment by razeitona** [comment]
It's not related. 
Because the metrics still with the same values except I go to the components that have recognized vulnerabilities in Dependency-Track and after press "Updated" in "View Details" then automatically appear in the metrics.

**Comment by Arunraj89** [comment]
@stevespringett : I am getting the below error while running it in mac os: 

`[{"message":"Scan must be Base64 encoded","messageTemplate":"Scan must be Base64 encoded","path":"scan","invalidValue":"$(cat /Users/pershingappsec/Documents/dependency-check-report.xml |base64 -)"}`

Is there any way/command to run it in **WINDOWS** system?

**Comment by stevespringett** [comment]
@Arunraj89 the Jenkins plugin would be one way to do it on Windows, but I'm not sure of any other way as I don't use it. One potential way is to use the Linux subsystem in Windows 10. I'm sure it has curl since you're basically running Ubuntu alongside Windows. But you may want to ask around to see what other people use to talk with REST APIs on Windows.

**Comment by Arunraj89** [comment]
Thanks, but what's abt the error I posted for macOS curl?

**Comment by Arunraj89** [comment]
@stevespringett : I am able to sussufully upload XML to D-Track using below code. Thanks for your support. 

`cat > payload.json <<__HERE__
{
  "project": "356323......",
  "scan": "$(cat dependency-check-report.xml |base64 -)"
}
__HERE__

curl -X "PUT" "http://localhost:8080/dtrack/api/v1/scan" \
     -k \
     -H 'Content-Type: application/json' \
     -H 'X-API-Key: id1NAqW....... \
     -d @payload.json`
