### ISSUE TITLE
purge unused components

### ISSUE THREAD

**Issue by stboissdev** [DependencyTrack/dependency-track#197]
add possibility to purge unused components

### Issue Type:
  - [ ] defect report
  - [x] enhancement request

**Comment by stevespringett** [comment]
Agreed, however, this should be a configurable option (possibly enabled by default).

**Comment by stevespringett** [comment]
Default behavior should be to have this feature **disabled** by default.

**Comment by msymons** [comment]
@stevespringett, is there any possibility that this enhancement might make it into 3.6?

I am afraid that the number of total components in my DT is climbing and climbing.  

![image](https://user-images.githubusercontent.com/4938718/61805728-373d3e80-ae2e-11e9-99b0-ed5363218e11.png)

It's hard to be sure how many are used and how many unused....  but DT does report that the total number of dependencies is virtually unchanging at 26,000.

Inspection shows that there many unused components  are SNAPSHOT components.  We also have a  rapid development environment where microservices (and their components) might iterate through multiple releases in a week.

It would be preferable if purge functionality could be configurable.  I would like to keep unused components that also have threats so that it is easier to spot when vulnerabilities pop up *after* previously having been considered to be addressed.

**Comment by stevespringett** [comment]
If something is going to make it into v3.6, I would rather implement an 'in-use' flag as defined in #364. That would allow you to make a REST call to discover the components that are not in use and perform some kind of action on them. And if you wanted to delete them, that's another REST call.

There's likely some data model changes for components that I'll want to make in a future release which would make this problem disappear without implementing purge functionality.

**Comment by msymons** [comment]
An 'in-use' flag sounds great for now.

**Comment by morganmccarley** [comment]
@stevespringett, this feature is of interest to me as well, any update on when such a flag will be implemented?  We haven't been using dependency track long enough to have a ton of bloat, but have already seen components that don't have an associated project.

**Comment by stevespringett** [comment]
Using the API to identify unused components and removing them is currently the only way.

The centralized component model was initially used because Dependency-Check was used for the majority of vulnerability analysis - and produced a lot of false positives. Having a centralized model made bulk auditing of false positives easy. 

That reality no longer exists. I've also been thinking about some of the weaknesses a centralized component model has and will likely be incorporating a hybrid model where each project has their own component definitions that tie back to a much smaller centralized model which wouldn't be directly used and could easily be auto pruned. The dependency graph capabilities (#280) and some of the integrity concerns I have over the existing model will be the driving factors for these changes. This issue will likely be a lucky recipient of the improvements.

I think this issue will eventually become unnecessary when this refactoring takes place, likely in the 3.8 or 3.9 timeframe.

**Comment by stevespringett** [comment]
The removal of unused components is working in the 593 development branch as part of the global model refactor.

**Comment by stevespringett** [comment]
Closing. Unused components are no longer possible with v4.0 - to be released soon.
