### ISSUE TITLE
Docker setup slow

### ISSUE THREAD

**Issue by razeitona** [DependencyTrack/dependency-track#199]
I've setup a server with dependency-track with docker however the server hangs and crash quite often.

**Comment by razeitona** [comment]
I'm running docker on a Windows Server 2016 with just Dependency-track on it
CPU 2.49
Memory 8gb ( 2gb reserved for docker, swap 1gb)
Disk 100gb with 64gb reserved for MobyLinuxVM image)

But it's really slow
 CPU %               MEM USAGE / LIMIT            NET I/O             BLOCK I/O           PIDS
  104.94%               1.658GiB / 1.934GiB      1.97MB / 7.78MB     4.56GB / 48.4MB     42

**Comment by stevespringett** [comment]
The minimum requirement for Dependency-Track is 4GB and 2 cpu cores. 

Due to issues with the Java Virtual Machine (in Java 8), the VM will actually report 8GB in your example as opposed to 2GB. Future Java versions will only report on the 2GB which would prevent Dependency-Track from running.

Due to the memory restrictions and Dependency-Track thinking it has 8GB when in reality only has 2GB, there's likely a lot of system swapping that's happening which would slow down the machine.

**Comment by stevespringett** [comment]
Closing
