### ISSUE TITLE
Documentation:  Incorrect Anchors in Changelog 

### ISSUE THREAD

**Issue by msymons** [DependencyTrack/dependency-track#2094]
### Current Behavior:

The Change Log for Dependency-Track can be found at: https://docs.dependencytrack.org/changelog/
The page contains multiple anchors.
The anchors are not unique and do not reference (say) version numbers.  Thus, the anchor for 4.5.0 release does not take one to 4.5.0 release.

### Steps to Reproduce:

1. Navigate to changelog URL (link above0
2. Scroll down to a specific release such as 4.5.0
3. Mouse-over the "#" symbol and right-click and select "open link in new tab"
4. Observe where you have been taken to.

### Expected Behavior:
* The anchor for 4.5.0 should take one to 4.5.0 release notes
* The anchor for 4.4.0 should take one to 4.4.0 release notes
etc

Instead, such anchors all point to: https://docs.dependencytrack.org/changelog/#software-bill-of-materials-sbom

Anchors for frontend-dist.zip (etc) are also not unique.

The reason why this is important is to avoid problems where the links are used in emails, blogposts, etc.  One wants to tell people "this was fixed in version X" and provide a URL that links to the correct changelog for X...  and have the link be valid in 6 months or 12 months time.

### Environment:
  
  - Dependency-Track Version: 4.6.1
  - Browser:  Firefox v106.0.1

**Comment by nscuro** [comment]
Support for Anchors was added in #1845, before that the docs had no anchors at all. IIRC, Jekyll does not come with proper support, and it's hard to retro-fit. So I am not sure how and if this can be fixed at all.

For Hyades we switched to MkDocs, which does a better job of generating working anchors. For example: https://dependencytrack.github.io/hyades/0.5.0-SNAPSHOT/operations/database/#bare-metal-docker

Assigning `size/S` nevertheless since changes to the docs shouldn't be too complex.
