### ISSUE TITLE
Make DependencyTrack HA. Or is it already?

### ISSUE THREAD

**Issue by micxer** [DependencyTrack/dependency-track#218]
Is there anything that prevents running at least two instances of DT in parallel accessing the same database? A use case would be a deployment in Kubernetes/OpenShift to have a HA setup that survives upgrades of the platform and faulty nodes.

**Comment by stevespringett** [comment]
Thinking out loud here... HA isn't something that's baked into Dependency-Track, although, I do think there's a way to achieve it.

A Dependency-Track node shouldn't contain much, only a self-executing war, Java, and the necessary OS files to run. So a node failure at the application level would only be caused by the shared filesystem or database. That's where you'd want to concentrate efforts to ensure it "_survives an upgrade_". All other failures should instantly trigger a new instance to spin up in place of the old.

Dependency-Track requires a data volume. This volume is NOT meant to be shared, but for an HA setup, there are a few things that must be shared. These include `/data/keys` and ideally, `/data/nist`. `/data/keys` contains public/private/symmetric keys used for encrypting/decrypting configuration as well as creating and validating JWT. You'll also want to replicate `/data/nist` so when the instances replicate the NVD, that they're updating the same dataset and not overwriting each other. All other data (files and directories) on the `/data` volume should NOT be shared between the instances.

Dependency-Track relies on DataNucleus for its persistence layer. By default, an internal L2 cache is enabled, but it does not support distributed caches. This can be changed and be pointed to Redis or Hazelcast for example. I haven't tried this, but they're both supported by DataNucleus. It can also be disabled. Changing the L2 cache to a distributed caching system or outright disabling the cache would be necessary. The default will cause problems.

Most database commits are atomic and occur either in a single commit or very small (single scoped) transaction. I don't foresee an issue in an HA setup.

Now... If your definition of HA also includes clustering of Dependency-Track nodes, that's where two or more running instances will run into a problem. Since commits are atomic, there's little need for pessimistic or optimistic locking. Although both methods of locking are supported by DataNucleus, Dependency-Track doesn't use either.

**Comment by torstenwalter** [comment]
For HA there are different things come to my mind:
- persistent file system
  - `/data/keys`
    Here you pointed out that `/data/keys` needs to be share because it contains public/private/symmetric keys. Is there a real need that multiple instances of dependency track access the same filesystem here or asking differently do they update this directory? Otherwise it would be simple to copy the content of that directory to all of the instances or share those things via a ConfigMap / Secret in terms of Kubernetes.

   - `/data/nist`
     I understand that it would make sense to share this directory between multiple application instances, to save bandwidth while downloading and also to ensure that all instances are working with the same data set. Is this used permanently when running the application or is it more a temporary staging area for downloaded files before those are processed and written into the database? In the later case sharing would not really be necessary, but one would need to coordinate which of the instances is updating the database. One could use the database as synchronization point here.
   - Are there any other directories which need to be shared?

- high available database
   Running multiple instances of the fronted, which are connected to the same database to make it HA just makes sense, if the DB is ha as well. I thinks that part could be left out of the discussion as there enough guides how to achieve this and it really depends on the actual setup. From dependency tracks point of view it's just a connection string.
- transactions
   When writing to the database do you see conflicting areas where one could run into trouble if two frontends are accessing the same database?
- session state / caching
   I would assume a load balancer in front of multiple frontends. Ideally one would not need sticky sessions as this makes it easier to scale and handle failures. That requires to think about where the information about the user being logged in is stored. e.g. Is it on the client (browser) side and can be validated by any of the frontends?
When load balancing requests to random frontends local caching could of course be an issue, meaning that depending on the state of the cache different information will be shown. You pointed out that the cache could be disabled altogether or be replaced by a distributed cache.

**Comment by stevespringett** [comment]
`/data/keys`
This directory will be written to on initial startup and only if the keys are not present. If the keys are present on startup, the three keys in this directory will only be read. Should be really simple to sync them across instances.

`/data/nist`
This directory is used to store the contents of the NVD mirror that it downloads from NIST. The embedded Dependency-Check instance will use this as its mirror. The mirror is also accessible as a mirror to other clients. The contents of this directory is updated every 24 hours when each instance will attempt to mirror and store the data there. 

> When writing to the database do you see conflicting areas where one could run into trouble if two frontends are accessing the same database?

Just the L2 caching issue I mentioned earlier. The persistence framework improves performance by caching objects and frequently used results. If these records are changes by another instance, there needs to be a way to inform the other instances. This is why I mentioned to either disable the L2 cache or to use a distributed cache, such as ehcache or hazelcast.

> Are there any other directories which need to be shared?

No. In fact, the other files/directories should NOT be shared as they will contain logs specific to the instance, temporary files, etc. 

> session state / caching

The caching I was referring to was persistence cache, not web cache. There shouldn't be any problem here. A load balancer should be fine. Dependency-Track doesn't use sessions. The web interface is a simple client to the REST API, which supports both JWT and API tokens. The web interface uses JWT and passes it with every request. The server validates the JWT and user permissions on every request. No sessions involved. The only requirement will be to ensure that all Dependency-Track instances are using the exact same version. So when upgrading, it's an all or nothing approach.

### Other notes
There's a lot of background processing tasks that an instance will perform. This includes:
* Mirroring the contents of the NVD (Every 24 hours)
* Mirroring the contents of NSP Public Advisories (Every 24 hours)
* VulnDB synchronizing (only when VulnDB is enabled) (Every 24 hours)
* Synchronizing LDAP users and group membership (Every 6 hours)
* Updating portfolio/project/dependency/component metrics (Every hour)
* Analyzes every component in the portfolio (Every 6 hours)
* Analyzes components for out-of-date (Every 24 hours)
* Performs vulnerability analysis (Every time a BoM is uploaded or a component is updated)

Ideally, the above tasks would only happen on a single instance in a cluster. Today, that's not the case. Every instance will do all this work. 

I've been toying with the idea of using JGroups as a way for multiple instances to communicate as well as a way to offload some tasks onto remote agents that accept incoming work. It would also be possible to proactively invalidate individual objects in L2 cache across all instances in the cluster without having to resort to disabling L2 or relying on an external distributed cache. This is all conceptual right now and would not end up in Dependency-Track until sometime next year.

**Comment by prabhu** [comment]
I tried to make a start on making this wonderful project k8s friendly in my personal fork (AppThreat/dependency-track). I could successfully comment out the memory and cpu count requirements in RequirementsVerifier and run the app with a node with ~ 3 GB RAM for weeks with a MySQL backend. Along with these directories related constraints, I think to make things scale we need to separate out the webapp from the API services and make it a bit modern if possible - which is going to be an effort since things have moved on the UI front from bootstrap 3 days :(

**Comment by stevespringett** [comment]
@prabhu fortunately, the UI is being rewritten from scratch. Refer to https://github.com/DependencyTrack/frontend. I'm hoping to have it ready in time for v3.8.

The memory and CPU requirements are there for a reason. On a fresh install, DT will consume 13GB of RAM while is parses and processes the millions of records that seed the database. Once seeded, daily update may also take this much. Although 8GB of RAM also is acceptable, but exhibits slightly slower performance. Performance for 4.5GB (the minimum recommended) is substantially slower than when running with 8 or 16. CPU requirements are there because of all the async background processing DT performs. On a large install with a lot of projects and components, if you only have a single CPU, the performance will likely impact all systems connected to it (notifications, CI/CD, etc).

So the UI will be a big improvement, but I also plan on creating some domain-specific services to help offload some of the non-BOM processing tasks. Metric updates, vuln-intel synchronization (e.g. NVD, VulnDB, and NPM mirroring) are examples of two services that should be broken out to their own services.

**Comment by prabhu** [comment]
Thank you for the clarification and for sharing the nextgen ui. Happy to take a look and contribute if possible.

If the db imports/refresh are RAM hungry, have you considered switching to the CVE 1.1 json format? I have another project (python based) that imports all the CVE json files into a database which can run with much lesser cpu and ram quota.

**Comment by oxdef** [comment]
According to `/data/` directory, is it correct to consider that only `/data/keys` can't be restored on the startup? If we deploy Dtrack in Kubernetes and in container image preserve only `/data/keys` will other content of  `/data/` directory be simply restored on container start?
