### ISSUE TITLE
[ScanUploadProcessingTask] Error while processing scan result

### ISSUE THREAD

**Issue by pbuckley4192** [DependencyTrack/dependency-track#219]
Logfile -> https://gist.github.com/pbuckley4192/2923d859294c70c570c0f662a8b23d36
jenkins reports that the xml file was sent sucessfully.
Updated the the Jenkins plugin to the latest, issue still persists.

DTrack Version: 3.3.0
Plugin Version: 3.4.0

File renamed to .txt because of github not accepting .xml
[dependency-check-report.txt](https://github.com/jeremylong/DependencyCheck/files/2542477/dependency-check-report.txt)

**Comment by stevespringett** [comment]
The issue has been fixed and will be available in the next release. Upon inspecting the dependency-check report though, there are thousands of components that will be added to the Dependency-Track project that don't have basic bom information (name, version, etc). They only consist of filenames and hashes. So the overwhelming majoring of dependencies being imported through this report cannot be properly analyzed. These dependencies being imported are actually just files inside an existing Node module. It appears the modules themselves are being imported, but due to the way Dependency-Check works, it will treat individual files as dependencies as well. So you get a ton of noise.

You may want to consider a pure BoM approach instead of importing dependency-check reports for this project (which is not the recommended approach anyway).

**Comment by stevespringett** [comment]
This issue is fixed in 3.4.0 and has been backported to 3.3.1 which is being released this week.
