### ISSUE TITLE
Detailed Report export option will be more helpful.

### ISSUE THREAD

**Issue by Arunraj89** [DependencyTrack/dependency-track#227]
### Issue Type:
  - [ ] enhancement request
  
### Current Behavior:
Currently we can view the issue with severity from Critical to Low, UI was good with more details than Dependency checker HTML report.

### Expected Behavior:
If we have a option to download report from Dependency Track means it will be more helpful. As D-Check don't show CRITICAL issues and more details as like D-Track

**Comment by stevespringett** [comment]
Dependency-Check doesn't show critical severity because it relies on CVSSv2 which doesn't support critical severity. Dependency-Check 4.0 will include support for CVSSv3 along with CPE 2.3 which will give it four severity categories (critical, high, medium, low). I don't know when 4.0 will be available. You'll have to ask Jeremy.

As for Dependency-Track, reports themselves are not actionable and are counter to the Dependency-Track strategy. It also doesn't have a reporting engine built into the platform. Everything is an API. If you want offline reports, I'd recommend leveraging the Findings API (in Dependency-Track v3.3.1) as it offers everything you'd likely need. In fact, v2.0 of the Jenkins plugin (released today) leverages this API as will all future external integrations (Kenna Security, Fortify SSC, etc).

**Comment by stevespringett** [comment]
An addition to the Findings API, the Finding Packaging Format which is being introduced in v3.4 may also be a solution. This is a simple API that can be called to retrieve a JSON file which contains everything from the Finding API along with project and application metadata so that external systems know what it is, what generated it, etc.

There are no plans to support the transformation of API data into externally consumed HTML, PDF, or other formats.
