### ISSUE TITLE
Frontend OIDC Configmap doesn't get created as part of Helm Chart

### ISSUE THREAD

**Issue by Gil-Tohar-Forter** [DependencyTrack/dependency-track#2322]
### Current Behavior

Part of Helm values.yaml is the frontend oidc configuration, which theoretically would get used to create the configmap with the config.json file of OIDC variables. However, the configmap isn't created.

I tried creating it manually to test out the feature, but it looks like the frontend docker image isn't making use of it.

### Steps to Reproduce

1. specify oidc values in values.yaml
2. deploy helm chart
3. confirm that oidc login option is not availabe

### Expected Behavior

1. specify oidc values in values.yaml
2. deploy helm chart, which then creates frontend configmap
3. oidc login gets enabled depending on avaibiliy of the required variablings

### Dependency-Track Version

4.6.x

### Dependency-Track Distribution

Container Image

### Database Server

PostgreSQL

### Browser

Google Chrome

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this defect was already reported

**Comment by syalioune** [comment]
Hello @Gil-Tohar-Forter, DT helm chart is maintained in [a different repository](https://github.com/evryfs/helm-charts/tree/master/charts/dependency-track). I suggest replicating the issue there and closing this one.
The helm chart does not indeed create a configmap for the frontend because of [a pending DT enhancement request](https://github.com/DependencyTrack/frontend/issues/60).

See https://github.com/evryfs/helm-charts/blob/master/charts/dependency-track/values.yaml#L22-L35

For the time being, [as stated in the documentation](https://docs.dependencytrack.org/getting-started/configuration/#frontend), you can provide OIDC configuration as environment variables in your helm values file.

**Comment by Gil-Tohar-Forter** [comment]
Thanks for the clarification. I will close this issue then

**Comment by Gil-Tohar-Forter** [comment]
Reopening as I am still experiencing issues:

I have set the environment variables for my OIDC issue and client_id. However, On the login page, I still see no OIDC login option in the UI after redeploying. I'm using the frontend environment variables

**Comment by syalioune** [comment]
Can you please confirm that you've also set the corresponding environment variables for the [API server](https://docs.dependencytrack.org/getting-started/openidconnect-configuration/) (i.e. ALPINE_OIDC_*) ?

Only setting the env on the frontend is not enough. The frontend calls the API /v1/oidc/available to check if the configuration is available and ok on the backend, and only then the OIDC will be enabled on the frontend.

You can check the result of that API call in your browser dev console (it should be 200).

**Comment by Gil-Tohar-Forter** [comment]
ah i didn't do that. I thought it was either setting frontend OR backend variables. I'll try that and report back.

**Comment by Gil-Tohar-Forter** [comment]
It worked. Thanks for the help
