### ISSUE TITLE
Repeated "server is not responding" in UI

### ISSUE THREAD

**Issue by msymons** [DependencyTrack/dependency-track#237]
### Issue Type:
  - [X ] defect report
  
### Current Behavior:
Dependency-Track Server is displaying an Error dialog every couple of minutes.  "The server is not responding.  Please try again or contact the administrator".

![image](https://user-images.githubusercontent.com/4938718/48781843-c1983600-ecd4-11e8-9ddd-b68113d1f489.png)

There is nothing in the server log apart from lots of healthy INFO events.

It seems that one does not have to be doing anything special for the dialog to pop up.  I have seen it appear the instant that I click on a link (although the code seems to indicate a timeout of 10 seconds).  I am also certain it also sometimes appear when I am not doing anything at all.  For instance, when writing this issue I navigated from dependency-track browser tab to GitHub and then back again...  and the error had popped up whilst I was looking at GitHub.

### Steps to Reproduce (if defect):
Cannot reproduce on demand.  For me, it just requires using the UI for more than a few minutes.
Perhaps network throttling as described [here](https://helpdeskgeek.com/networking/simulate-slow-internet-connection-testing/) might help?

### Expected Behavior:
Less timeouts.  Perhaps via configurable timeout?  This might help for slow connections 
If usage of H2 database could be playing a role, then perhaps add a line or two to documentation to recommend limitations on number of projects, etc.

### Environment:
  
  - Dependency-Track Version: v3.3.1
  - Distribution: [ Executable WAR]
  - Database Server: [ H2 ]
  - Browser: Firefox v63.0.1
  - Slow network..  awaiting a VPN upgrade!
 - Projects 8 (only 6 are analysed) with 917 components.
 

### Other Details:
N/A

**Comment by stevespringett** [comment]
I've also seen this occasionally on localhost while developing. Have not been able to reproduce on-demand. But have found that a reload of the page typically solves it, whatever the problem was. I have not noticed anything in the logs that would point me in any specific way. And have not gone out of my way to try to figure it out yet. Not sure if it's server-side timeouts or related to jQuery flaking out.

It's not related to H2. While H2 should not be used for production, I have tested it with thousands of projects, tens-of-thousands of components, and double the number of vulnerabilities (250K+).

**Comment by msymons** [comment]
I should have said in my original report that the Error seems to cause no problem - other than annoyance.  I have not found it necessary (yet) to have to reload a page; just dismiss the Error dialog and carry on.

After logging the defect I did see the Error reproduce reliably in one way...

Having generated a dozen CycloneDX BoM files (but not yet having implemented automatic synch in Jenkins pipelines), I manually created over a dozen new projects and then, one by one, entered each individual project page to upload a BoM.  Anyway, after clicking on the project's "Dependencies" tab, I found that I could then just wait, and then the Error would pop up 10 seconds later.   Bear in mind that the Dependencies page was empty of data at this time (no BoM yet uploaded).

The 1st couple of times I had gone straight to upload...  thus thinking that it was clicking upload that was the problem (because the error would display almost as soon as I started to work with the upload dialog).   But, this was a red herring....  the Error would always display +/- 10 seconds after completing the previous action (navigating to Dependencies tab).  

I know that there are occurrences of the Error dialog in other places, so I guess that reproduction can be a pain... because users wont be pausing 10 seconds between each click of the mouse and thus confusing the error with what they are doing now as opposed to what they were doing 10 seconds earlier.

Could additional logging help?  Perhaps at lower level than INFO?  After talking to colleagues last week, I was actually already intending to create a new enhancement request suggesting that it would be useful to be able to configure log level and log rollover!

**Comment by msymons** [comment]
You are correct that it's not related H2. With our Dependency-Track installation now migrated from using H2 to using PostgreSQL, the timeouts continue.

I used the Developer Tools in Firefox and it seems that there is consistently one request that take longer than anything else to serve...
```
https://foo.bar.com/api/v1/license?offset=0&limit=1000
```
Mostly over 10 seconds, but I have definitely seem a couple of "8.x" second examples where the timeout dialog still displayed....  but in these cases the *total* page load time was still over 10 seconds.

**Comment by msymons** [comment]
@stevespringett, some more info.

When the "server is not responding" errors occur, the consequence is that it is not possible to edit the license for a component...  the drop-down is empty (on the occasions when it is not displaying a "red circle with diagonal" tooltip).  

When the error occurs, Firefox Developer tools always reports that `api/v1/license?offset=0&limit=1000` response is a different size...  eg 2 MB, 3 MB, 5 MB.

When there is no error then Firefox Developer tools reports that `api/v1/license?offset=0&limit=1000` is 7.07 MB.

There are no "server is not responding" errors when connecting to Dependency-Track server using a browser on a host that is local to Dependency-Track (ie, remove slow VPN link from the equation).

We therefore edited the timeout within `dependency-track-embedded.war` from 10000 to 100000

**This caused the errors to STOP and we can now edit licences, even when connecting via the VPN!**

I suggested above that it might be useful to expose timeout as a configuration parameter.  But a 7MB download that is occurring dozens of times per session is still a lot of traffic.
 - Could license.json be compressed?
-  Could it be cached by the browser?

**Comment by stevespringett** [comment]
Thank you for tracking that down. The license text for each license was being returned. This was one of the first APIs developed for the new platform and hasn't been revisited since, so things got overlooked. The license contents, as you can imagine, is quite large and completely unnecessary for use with a dropdown when only minimal data is required.

I created a new License API (/license/concise) that will only return the most commonly used fields without the full text of the license. The 7MB response is now just 65KB.

In addition to the time necessary to download 7MB was the time necessary for the browser to parse it and update the DOM based on some of its contents. The time the browser takes to parse the file after download will also be considerably less now.

I've also increased the jQuery timeout from 10 seconds to 60 seconds.

If you have capacity, please try out the master branch, but NOT ON PRODUCTION DATA and let me know your experience.

These fixes will be available in v3.4 with an expected ETA of late December or early/mid January.

**Comment by msymons** [comment]
I'm glad that I was able to help find the source of the problem.  It sounds like the fix will help a lot with UI performance.

I'm afraid that I probably won't have capacity to try out the master branch:  now that I worked around the problem in v3.3.1 by tweaking the timeout, I have about 500 components with no reported licences that I need to research and update in Dependency-Track!

**Comment by stevespringett** [comment]
Understood, and thanks again. If you find there's a repetitive task you're doing that could be implemented in Dependency-Track to help with license identification, let me know.

I'm going to close out this ticket. If you experience the same issues after the launch of 3.4, go ahead and reopen.
