### ISSUE TITLE
Password Save prompt when navigating away from Administration

### ISSUE THREAD

**Issue by msymons** [DependencyTrack/dependency-track#256]
### Issue Type:
  - defect report  (minor)
  
### Current Behavior:
When visiting the "Administration" tab in Dependency-Track,  a browser "password save" dialog is displayed when subsequently navigating away from Administration.  There is no prompt whilst twitching screens within Admin (eg, moving from "Access Management" to "Notifications"...   it only pops up when clicking on (say)  "Components" tab

 - The password save dialog has "no username" displayed for user.
 - For password, we can click on "show password" and see that the value is "HiddenDecryptedPropertyPlaceholder".

The behaviour is an annoyance and does not affect functionality.  I always just dismiss the dialog.  Thus, minor defect.

### Steps to Reproduce (if defect):
See above.

### Expected Behavior:
There should be no "password save" prompt displayed by the browser when working in "Administration" and then switching to another tab.

### Environment:
  
  - Dependency-Track Version: 3.3.1
  - Browser:  Firefox 63.0.3

**Comment by stevespringett** [comment]
Browsers suck. They follow standards when it suites them, and ignore standards (i.e. autocomplete) when they feel like it. Nothing I can do about Firefox behavior other than to recommend that Firefox not be configured to save passwords.

I have some changes that may or may not work - basically, these changes recreate the purpose of the password field without actually using a password field. Hopefully this will solve the issue. I could not reproduce because my Firefox (even when configured to save passwords) did not prompt me.

**Comment by msymons** [comment]
Tested Dependency Track v3.4.0 using Firefox v64.0 and the problem seems to be resolved... there is no longer a "password save" dialog displayed when navigating away from the Administration tab.
