### ISSUE TITLE
missing positive identification for commons-collections 3.2.1

### ISSUE THREAD

**Issue by garretfick** [DependencyTrack/dependency-track#259]
### Issue Type:
  - [x ] defect report
  - [ ] enhancement request
  
  
### Current Behavior:
Dependency track shows different vulnerabilities compared to OWASP's dependency check

### Steps to Reproduce (if defect):
1. Create a new project
2. Update the attached dependency file
3. When analysis finishes, notice that the dependency is not listed even though there is a known issue (OWASP Dependency Check does identify the component as vulnerable)

### Expected Behavior:
1. Identifies known vulnerability

### Environment:
  
  - Dependency-Track Version: snapshot (2018-12-17)
  - Distribution: Docker
  - BOM Format & Version: Cyclone DX (attached file)
  - Database Server: PostgreSQL
  - Browser: Chrome

[bom.zip](https://github.com/DependencyTrack/dependency-track/files/2691465/bom.zip)

### Other Details:
(e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by stevespringett** [comment]
Thanks for identifying this issue with OSSIndex. While we wait on the to fix it, I may have a workaround. Basically the strategy would be to strip off any qualifiers or subpaths from a PackageURL so that OSSIndex can process it. The `?type=jar` is a qualifier in PackageURL terms. By omitting these non-relevant aspects from the Purl, we may have a workaround until OSSIndex creates a proper fix.

I have a bit more testing to do, but this is likely something I can target for 3.4 being released in the next day or two.

**Comment by garretfick** [comment]
OSSIndex has fixed the underlying issue, so the workaround can be removed.
