### ISSUE TITLE
Table Sort Displays Incorrect Data In Other Columns

### ISSUE THREAD

**Issue by msymons** [DependencyTrack/dependency-track#267]
### Issue Type:
  - [X] defect report
  - [ ] enhancement request
  
### Current Behavior:
Table Sorting was introduced in v3.1.0 (See #109).

Testing in v3.4.0, using sort is resulting in incorrect data being displayed in other columns.  ie, for components,  sorting by Group is breaking version, risk, and vulnerabilities.

This can be seen in this example for Project -> Dependencies.

![image](https://user-images.githubusercontent.com/4938718/51338190-1a8c0c80-1a81-11e9-920a-be532bc7f73f.png)

The problem does also affect Projects (summary) page where sorting by "Last BOM Import" breaks vulnerabilities.

### Expected Behavior:
Sorting should result in columns "keeping in synch"

### Environment:

  - Dependency-Track Version:  3.4.0
  - Distribution: [Executable WAR]
  - Database Server: [PostgreSQL]
  - Browser:  Firefox v64.0.2

**Comment by stevespringett** [comment]
Do you have a BOM that produces the data that's getting out of sync? I'm unable to replicate.

**Comment by msymons** [comment]
BOM sent via Slack on 26 April 2019.
I hope that it helped.

**Comment by msymons** [comment]
@stevespringett,  I have replicated the sort issue in 3.5.0-SNAPSHOT (Built-on:  2019-05-22T16:22:23Z) using the 428-component BOM sent via email to you on 22 May 2019.

![image](https://user-images.githubusercontent.com/4938718/58267115-de442200-7d7a-11e9-8af5-d97eeba161fc.png)

One observation for the behaviour displayed in this screenshot...  when the sort is "broken" and I then use search to filter the components, then things seem to improve.    eg filter by "addressing" and only the single component is displayed and not the three shown in the screenshot.

**Comment by msymons** [comment]
Separately, should not component sort be case-insensitive?

it seems to be case-insensitive in v3.4.1 and case-sensitive in v3.5.0-SNAPSHOT.

This results in oddities for (say):

`pkg:maven/org.apache.ws.commons.schema/XmlSchema@1.4.3?type=jar`

**Comment by stevespringett** [comment]
Replicated. Looking for solution.

**Comment by stevespringett** [comment]
The issue appears to be some kind of async race condition which I don't completely understand. Vulnerability metrics and outdated status are all individual requests being made with anonymous functions which _should_ update the associated html when returned. There appears to be async issues here, perhaps with one of the libraries in use. Not exactly sure.

However, if there are 10 dependencies displayed on initial load (the default), then for each of those, the browser was making 10 additional requests for outdated status and 10 more for vulnerability metrics. So, instead of worrying about fixing the async issue, I'll be transitively including metrics and outdated stats since they all require the same permissions. This should speed up rendering times and will result in accurate display regardless of sorting.

The fix is about half complete, but I need to include outdated stats and check the rest of the UI to see if there are any other occurrences on other pages that I can see.
