### ISSUE TITLE
packages.config duplication in results

### ISSUE THREAD

**Issue by Drewster727** [DependencyTrack/dependency-track#269]
#134 seems related to this, but that issue is locked.

### Issue Type:
  - [x] defect report
  - [ ] enhancement request
  
  
### Current Behavior:
Lots of duplicates, seems to be specific to packages.config
![image](https://user-images.githubusercontent.com/4528753/51497036-7a3b2e00-1d87-11e9-85b9-624e773b120a.png)

### Steps to Reproduce (if defect):
@stevespringett I will send you the dependency-check-report.xml file

### Expected Behavior:
Multiple expectations
- packages.config should not show up at all (but should be scanned in the dep check)
- it should not show the full path of the file
- it should not duplicate

### Environment:
  
  - Dependency-Track Version: 3.4.0
  - Distribution: Docker
  - BOM Format & Version: dep check xml 4.0.2
  - Database Server: built-in, H2?
  - Browser: chrome

### Other Details:
I logged what the dep check tool was doing. Will provide separately.

**Comment by Drewster727** [comment]
@stevespringett emailed you xml and log separately. Thanks.

**Comment by stevespringett** [comment]
Dependency-Check doesn't do a good job at being a bill-of-material. It's not designed for that. Although you can import DC reports, the quality of what's in the reports matters a great deal. GIGO

packages.config was imported because it was listed in the report. It shows the filename because a component needs a 'name' and nothing else was provided in the report that could be used as a name. If the filename is the full path in the dependency-check report, it will be the full path when importing.

Refer to https://docs.dependencytrack.org/best-practices/ for best results.

**Comment by Drewster727** [comment]
@stevespringett  Understood. We'd love to use cyclonedx but have ran into issues right out the gate, which I have an open issue on (cyclonedx-dotnet). Any other options? We're going with the DC approach for now...

**Comment by stevespringett** [comment]
Also understood. I will try to figure out the dotnet issue tonight - received an out-of-band email from you with the contents. My time is limited this week with travel and AppSec Cali stuff. But I'll try to reproduce and get a working CycloneDX impl for you.

DC is certainly better than nothing. Java projects provide the best quality bill-of-material data IMO.

**Comment by Drewster727** [comment]
Thanks for work on all of this @stevespringett -- it is much appreciated.
