### ISSUE TITLE
Add missing support for supplier and manufacturer

### ISSUE THREAD

**Issue by stevespringett** [DependencyTrack/dependency-track#2737]
### Current Behavior

DT does not support supplier on the component or supplier and manufacturer at the metadata level. This is an oversight as `OrganizationalEntity.java` was created for this purpose and is used by CycloneDX service to support providers. But OrganizationalEntity was never added to the BOM or component objects.

### Proposed Behavior

Add support for supplier on the component and supplier and manufacturer at the BOM metadata level.

Considering this is an NTIA minimum requirement, this needs to be added asap.

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this enhancement was already requested

**Comment by stevespringett** [comment]
Related to #2373

**Comment by leec94** [comment]
is this completed now with the merged PR? @nscuro

**Comment by nscuro** [comment]
Hey @leec94, I found a few wrinkles while dabbling around locally:

1. [As per CDX spec](https://cyclonedx.org/docs/1.5/json/#components), components have only suppliers, but no manufacturers. The current implementation has both assigned to `Project` and `Component`, but `manufacturer` can never be populated for those.
2. [`metadata.manufacture`](https://cyclonedx.org/docs/1.5/json/#metadata_manufacture) and [`metadata.supplier`](https://cyclonedx.org/docs/1.5/json/#metadata_supplier) in the spec map to `Bom#manufacture` and `Bom#supplier` respectively. The current implementation however assigns `metadata.manufacture` to `Project#manufacture`, and `metadata.component.supplier` and  `metadata.supplier` are ignored entirely.
3. We need changes in the frontend to display this information. [`ComponentDetailsModal`](https://github.com/DependencyTrack/frontend/blob/master/src/views/portfolio/projects/ComponentDetailsModal.vue) and [`ProjectDetailsModal`](https://github.com/DependencyTrack/frontend/blob/master/src/views/portfolio/projects/ProjectDetailsModal.vue) must be extended with a *Supplier* tab. We have something similar for service providers in [`ServiceDetailsModal`](https://github.com/DependencyTrack/frontend/blob/9b44da76dcdf1ada12c90741b04e8238102776d0/src/views/portfolio/projects/ServiceDetailsModal.vue#L33-L58) already.

Another more general complication I'm seeing: If `metadata.manufacturer` and `metadata.supplier` map to the `Bom` model in DT, then how should DT behave when exporting a project as CycloneDX again? 

The relationship between `Bom` and `Project` in DT is `N:1`, and because projects can be edited manually there is no guarantee that the last uploaded BOM still represents reality. Also, binding these attributes to `Bom` means that users will never be able to manually craft `manufacturer` and `supplier` data in DT, without having uploaded a BOM before.

@stevespringett, any thoughts? I think we may need a new table to track this kind of metadata. That table would then also hold things like tools, lifecycle, authors, etc. in the future.

**Comment by nscuro** [comment]
Ah, found this https://github.com/DependencyTrack/dependency-track/issues/2373#issuecomment-1380713220:

> These things could also be asserted in a BOM and *we should likely store them somewhere related to the project*, but also lock them so that they cannot be modified.

I think that answers my question. So separate table it is.

**Comment by nscuro** [comment]
OK I may have gotten it wrong again.

It seems like `metadata.manufacturer` would indeed map to `Project#manufacturer`. But `metadata.supplier` would be something separate from `Project`, because there's already `metadata.component.supplier` that maps to `Project#supplier`.

So something along the lines of:

![image](https://github.com/DependencyTrack/dependency-track/assets/5693141/32838dde-2055-4efa-aa7e-059e42d39a8c)
