### ISSUE TITLE
False negative with spray-json 1.3.4

### ISSUE THREAD

**Issue by potsec** [DependencyTrack/dependency-track#274]
### Issue Type: 
defect report
  
  
### Current Behavior:
- Uploaded a CycloneDX BOM for a Scala project which includes spray-json_2.12 version 1.3.4.
- There are a few CVEs in NVD which apply to 1.3.4 and below (eg CVE-2018-18853): https://discuss.lightbend.com/t/spray-json-1-3-5-security-fix-released/2663
- These CVEs do show up in the dependency track vulnerability list
- The BOM shows version 1.3.4 and Dependency Track correctly shows that version for the project in the UI
- However, the vulnerability does not get indicated for that component. 

### Steps to Reproduce (if defect):
As above.

### Expected Behavior:
Expecting the vulnerabilities to be identified for that component

### Environment:
  
  - Dependency-Track Version: v3.4.0
  - Distribution: Docker
  - BOM Format & Version: cyclonedx.org/schema/bom/1.0
  - Database Server: PostgreSQL
  - Browser: Chrome

I have OSS-index enabled.

### Other Details:
BOM:
```
...
        <component type="library">
            <group>io.spray</group>
            <name>spray-json_2.12</name>
            <version>1.3.4</version>
...
```
![image](https://user-images.githubusercontent.com/37295917/51973967-c3ba0600-2476-11e9-9e93-e51dd5bb04ba.png)

![image](https://user-images.githubusercontent.com/37295917/51974036-f106b400-2476-11e9-84ae-bbdf470ada6a.png)

**Comment by stevespringett** [comment]
If Dependency-Check is enabled, try disabling it. The false positive likely came from that.

Also, verify that the component is not being flagged as vulnerable from OSSIndex. You can do this directly from their website. If it is, please contact OSSIndex via email to report it.

Dependency-Track doesn't have a native analyzer. It relies on Dependency-Check, OSSIndex, and NPM Audit for this. Therefore, no actions are taken on false positives.

Refer to:
https://docs.dependencytrack.org/triage/auditing-basics/
https://docs.dependencytrack.org/triage/dependency-check/
https://docs.dependencytrack.org/best-practices/

**Comment by msymons** [comment]
@stevespringett, this issue was reported for a false negative, and not a false positive. 

I have spotted a separate false negative for npm with Dependency-Track v3.4.0, having uploaded a BOM containing:

```
        <component type="library">
            <name>ejs</name>
            <version>2.3.4</version>
            <description>
                <![CDATA[Embedded JavaScript templates]]>
            </description>
            <hashes>
                <hash alg="SHA-1">3c76caa09664b3583b0037af9dc136e79ec68b98</hash>
            </hashes>
            <licenses>
                <license>
                    <id>Apache-2.0</id>
                </license>
            </licenses>
            <purl>pkg:npm/ejs@2.3.4</purl>
            <modified>false</modified>
        </component>
```
DT lists one threat (CVE-2017-1000228).
Also:
https://www.npmjs.com/package/ejs/v/2.3.4 
https://ossindex.sonatype.org/component/pkg:npm/ejs 

There is one wrinkle in my usage....

I only have the one npm project.

- The BOM was initially uploaded in December 2018 to DT v3.3.1.  
- The npm analyser was then disabled to resolve CPU problems... but we had a nominally succesful analysis of the project with 6 npm threats identified (none for ejs).
- After upgrading to v3.4.0, the OSS Index analyser was enabled in mid January and Dependency-Check was disabled.
- DT reports Last Measurement = "12 Feb 2019 at 12:41:42  "

So, if npm analysis failed to warn, I would still have expected the threats to have been picked up by the  OSS Index analyser when it was enabled.  Does that make sense?

**Comment by stevespringett** [comment]
@msymons Is OSSIndex configured with proper authentication details? Vulnerabilities are only available to authenticated users.

**Comment by msymons** [comment]
I *think* it's configured with proper authentication details.  I used the same combination (email address + token) that worked fine when testing the [REST API](https://ossindex.sonatype.org/rest/) 

This is why I logged #265, suggesting that a "Test Connection" button would help.  Per that issue,  I performed additional testing of the OSS Index REST API that shows that the `/api/v3/version` endpoint does respond to authenticated requests (returning HTTP 200 or 401 as appropriate).

**Comment by stevespringett** [comment]
I'm unable to reproduce. The four vulnerabilities are properly identified via OSSIndex when NPM Audit is disabled.

<img width="1235" alt="screen shot 2019-02-12 at 10 15 05 am" src="https://user-images.githubusercontent.com/3878933/52650281-8eb6a600-2eaf-11e9-9bcb-b2eb5a077362.png">

**Comment by msymons** [comment]
Excellent!  I'll dig into things next week in the hope/expectation that the missing vulnerabilities will appear once I get OSS Index authentication working.

**Comment by stevespringett** [comment]
Closing.
