### ISSUE TITLE
Docker images not tagged consistently

### ISSUE THREAD

**Issue by calderonth** [DependencyTrack/dependency-track#2946]
### Current Behavior

I have observed that the docker hub images do no seem to be tagged/released in parallel.

For instance `4.8.2` was released in May and is available at https://hub.docker.com/r/dependencytrack/apiserver but the frontend docker image is only at version `4.8.1` https://hub.docker.com/r/dependencytrack/frontend.

Is there a reason they are disjoint?

Thanks

### Proposed Behavior

When a new release is cut, all docker images bumped to the same release tag.
This could be done via Github action if it's not already the case.

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this enhancement was already requested

**Comment by antoinbo** [comment]
Hi @calderonth, from what I see the docker images are tagged according to project repositories' releases, last frontend release is currently `4.8.1`. I would not like to increment the version number for no change and spend time deploying a empty update just because minor version numbers are not matching.

**Comment by calderonth** [comment]
Got it, I hadn't immediately realised the frontend was released through a separate project.
