### ISSUE TITLE
Enable portfolio access control doesnot work as intended

### ISSUE THREAD

**Issue by visagansanthanam-unisys** [DependencyTrack/dependency-track#2964]
### Current Behavior

Even when we enable portfolio access control and grant access for individual teams, all users are able to view all projects irrespective of the team they belong to.
![image](https://github.com/DependencyTrack/dependency-track/assets/100369838/d40726c7-e1dd-4305-ab53-a65318e4bd7f)
![image](https://github.com/DependencyTrack/dependency-track/assets/100369838/ff6123e5-965a-4e9a-a24e-e425796c9d39)

### Steps to Reproduce

1. Enable Portfolio access control
2. Create two teams and grant access to separate projects for each team, both team should not have access to the same project
3. Add users to the teams
4. Ask the user to login into the application
5. The user would see two projects instead of one mentioned in the Portfolio access control

### Expected Behavior

Portfolio access control should enable administrators to provide granular role-based access at the project level.

### Dependency-Track Version

4.8.0

### Dependency-Track Distribution

Container Image

### Database Server

PostgreSQL

### Browser

Google Chrome

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this defect was already reported

**Comment by rkg-mm** [comment]
Since I am using this feature without any issues in a lot of projects, I doubt there is a bug as described.
Please check:
* Are the users in any other groups  too (e.g. Administrators?) If yes, which permissions do these groups grant?
* Which permissions do the users have generally?

If I remember correct, the dashboard metrics do show ALL projects, regardless of ACLs, but this is a known bug that is tracked somewhere from what I remember. The list of projects is working fine with ACLs for me.

**Comment by visagansanthanam-unisys** [comment]
@rkg-mm Thanks for the information. The issue was with the users being part of multiple teams with different project access. its working once I cleared and reconfigure the ACL.
