### ISSUE TITLE
DT doesn't report a given CVE for busybox component

### ISSUE THREAD

**Issue by groetingc** [DependencyTrack/dependency-track#2994]
### Current Behavior

When uploading a valid SBOM which includes a busybox 1.34.1 component entry, it should find this CVE:
https://nvd.nist.gov/vuln/detail/CVE-2022-48174

### Steps to Reproduce

1. Upload SBOM such as:
`{ "bomFormat": "CycloneDX", "specVersion": "1.4", "serialNumber": "urn:uuid:fefa5aa8-6e7a-4045-9839-3daadf08e8db", "version": 1, "metadata": { "timestamp": "2023-08-29T09:36:12+02:00", "component" : { "type" : "firmware" } }, "components": [
{
"name": "wpa_supplicant",
"version": "0.7.3",
"licenses" : [ { "license" : { "id" : "GPL-2.0" } } ],
"cpe": "cpe:2.3:*:w1.fi:wpa_supplicant:0.7.3:*:*:*:*:*:*:*",
"type": "library"
},
{
"name": "Expat XML Parser",
"version": "2.2.6",
"licenses" : [ { "license" : { "id" : "MIT" } } ],
"cpe": "cpe:2.3:*:libexpat_project:libexpat:2.2.6:*:*:*:*:*:*:*",
"type": "library"
},
{
"name": "Dropbear SSH",
"version": "2019.78",
"licenses" : [ { "license" : { "id" : "Dropbear-SSH-License" } } ],
"cpe": "cpe:2.3:*:dropbear_ssh_project:dropbear_ssh:2019.78:*:*:*:*:*:*:*",
"type": "library"
},
{
"name": "BusyBox",
"version": "1.34.1",
"licenses" : [ { "license" : { "id" : "GPL-2.0" } } ],
"cpe": "cpe:2.3:*:busybox:busybox:1.34.1:*:*:*:*:*:*:*",
"type": "library"
}
] }`

3. Check if CVE-2022-48174 will be listed in list of found Vulnerabilties

### Expected Behavior

Based on https://nvd.nist.gov/products/cpe/detail/4F44139D-44A7-401C-BEA9-6FAFA543C015?namingFormat=2.3&orderBy=CPEURI&keyword=cpe%3A2.3%3Aa%3Abusybox%3Abusybox%3A1.34.1%3A*%3A*%3A*%3A*%3A*%3A*%3A*&status=FINAL%2CDEPRECATED the cpe match should lead to a valid entry.

This is the result from a nvd.nist.gov query:
https://nvd.nist.gov/vuln/search/results?adv_search=true&isCpeNameSearch=true&query=cpe%3A2.3%3Aa%3Abusybox%3Abusybox%3A1.34.1%3A*%3A*%3A*%3A*%3A*%3A*%3A*

### Dependency-Track Version

4.8.2

### Dependency-Track Distribution

Container Image

### Database Server

H2

### Browser

Google Chrome

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this defect was already reported

**Comment by Jasper-Ben** [comment]
Question:
Shouldn't this be `:*:*:*:...`, instead of `:::...`, resulting in `cpe:2.3:*:busybox:busybox:1.34.1:*:*:*:*:*:*:*`

Regardless of that, the underlying issue you are facing is the one I reported here: https://github.com/DependencyTrack/dependency-track/issues/2988, which causes the IMO questionable behavior that you will get false negatives, if your components CPE contains `*` in an attribute where the CVE CPE contains a value.

You can reproduce this behavior by manually changing your component cpe to contain the `a` value for the `Part` attribute of the CPE: `cpe:2.3:a:busybox:busybox:1.34.1:*:*:*:*:*:*:*` and doing a re-scan. Now it will match.

Again, I do not agree with this behavior, as it WILL hide security risks to your application portfolio, however the project maintainers seem to be under the impression that avoiding potentially false positives due to incomplete component CPEs is more important than showing potential security risks, even though they might be false negatives due to incomplete component CPE data.

**Comment by groetingc** [comment]
@Jasper-Ben : Yes, sorry, the stars are removed when not using `code` formatting in the ticket, but yes this is what my SBOM generator is putting into DT: `cpe:2.3:*:busybox:busybox:1.34.1:*:*:*:*:*:*:*`
I can confirm that when changing to `cpe:2.3:a:busybox:busybox:1.34.1:*:*:*:*:*:*:*` DT detects that missing CVE! 
Also, I fully agree with Your findings related to the usage of a wildcard instead of a dedicated value, which our SBOM generator is not aware of. In Yocto:dunfell they generate the CPEs out of the recipes using an 'a' as default for the generated CPE. This has lead to not finding any CVE related to linux-kernel because that expects to have an 'o' instead. not finding any issues for the kernel is a no-go. 
With commit: https://git.yoctoproject.org/poky/commit/meta/lib/oe/cve_check.py?id=92983dba651cffe5c11973d90aad00c581a79c93
in latest Yocto versions, they will generate the CPE using a '*' which will then still lead to probably many CVEs not found by DT. That will strongly reduce the trust in the tooling.

**Comment by Jasper-Ben** [comment]
> In Yocto:dunfell they generate the CPEs out of the recipes using an 'a' as default for the generated CPE. This has lead to not finding any CVE related to linux-kernel because that expects to have an 'o' instead. not finding any issues for the kernel is a no-go.
With commit: https://git.yoctoproject.org/poky/commit/meta/lib/oe/cve_check.py?id=92983dba651cffe5c11973d90aad00c581a79c93
in latest Yocto versions, they will generate the CPE using a '*' which will then still lead to probably many CVEs not found by DT. 

I am actually the author of that commit, so I am fully aware of the issue. In addition to the issue opened here, I also posted the following on the openembedded mailing-list, with the aim to include more details in the CPE data provided by openembedded-based projects: https://lists.openembedded.org/g/openembedded-core/topic/100962508#186724 Regardless of the dependency-track issue, openembedded should provide more data to avoid false positives (i.e. the linux kernel has some HW architecture specific CVEs).

So yes the issue is twofold:

1. dependencytrack not reporting on potential positives
2. openembedded/yocto (and probably other tools) not providing detailed information.

> That will strongly reduce the trust in the tooling.

Fully agree with you. I hope the maintainers of DT will reconsider their stance on this. Frankly what concerns me is that DT seemingly is not fazed by the fact that their tool that should provide the solid foundation for determining the safety of your application actively hides security issues in favor of the "UX" of not having false positives reported.

**Comment by Jasper-Ben** [comment]
For visibility: we are working on fixing this defect, as part of https://github.com/DependencyTrack/dependency-track/issues/2988

@nscuro do you want to close this as a duplicate?
