### ISSUE TITLE
DT memory usage increasing over time till the application restarts

### ISSUE THREAD

**Issue by cryptator** [DependencyTrack/dependency-track#3225]
### Current Behavior

We have hosted dependency-track over a kubernetes pod (single replica) using Postgres as DB with over 600 projects.
Allocated resources are : 16GB RAM and 4 CPU and no limits set.
We have observed that the memory consumption of the app continuously goes up to 30 GB before the pod get unstable (unhealthy) and a new pod comes up.
![image](https://github.com/DependencyTrack/dependency-track/assets/13695480/abda8f71-e424-4844-badf-4825204275bf)

I also took a heap-dump and analyzed it using MAT, where the heap consumption was due to `org.datanucleus.cache.SoftLevel2Cache`, here is a snapshot:
![image](https://github.com/DependencyTrack/dependency-track/assets/13695480/1bb5fd05-41a9-4825-8ae3-8ecff3d2fa29)

In the logs I can see some warning related to `The index * does not exist` where * is PROJECT, COMPONENT, VULNERABILITY, LICENSE, CPE, etc. and a few errors:
```
An error occurred while parsing NVD JSON data
Caused by: org.postgresql.util.PSQLException: An I/O error occurred while sending to the backend.
javax.jdo.JDODataStoreException: An I/O error occurred while sending to the backend.
non-transactional - Connection org.postgresql.jdbc.PgConnection@42ba86b2 marked as broken because of SQLSTATE(08006), ErrorCode(0)
org.postgresql.util.PSQLException: An I/O error occurred while sending to the backend.
```
There aren't any other errors.

What can be the cause of this memory increase? Can there be a memory leak somewhere because of which this is happening?

### Steps to Reproduce

1. Deploy DT and load 600 applications with a lot of components.
2. Wait to see the memory consumption continuously increase.
3. This will reach a point where the application does not respond.

### Expected Behavior

The application memory stays nearly the same throughout the application lifecycle.

### Dependency-Track Version

4.9.1

### Dependency-Track Distribution

Executable WAR

### Database Server

PostgreSQL

### Database Server Version

15.3

### Browser

N/A

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this defect was already reported

**Comment by nscuro** [comment]
Looks like you're running into issues caused by the ORM's level 2 cache. It will be disabled in a future version of DT by default, for now you can do it [manually](https://docs.dependencytrack.org/getting-started/configuration/):

```ini
# Optional
# Controls the 2nd level cache type used by DataNucleus, the Object Relational Mapper (ORM).
# See https://www.datanucleus.org/products/accessplatform_6_0/jdo/persistence.html#cache_level2
# Values supported by Dependency-Track are "soft" (default), "weak", and "none".
#
# Setting this property to "none" may help in reducing the memory footprint of Dependency-Track,
# but has the potential to slow down database operations.
# Size of the cache may be monitored through the "datanucleus_cache_second_level_entries" metric,
# refer to https://docs.dependencytrack.org/getting-started/monitoring/#metrics for details.
#
# DO NOT CHANGE UNLESS THERE IS A GOOD REASON TO.
# alpine.datanucleus.cache.level2.type=
```

So, setting via environment variable would be:

```env
ALPINE_DATANUCLEUS_CACHE_LEVEL2_TYPE=none
```

In my experience, disabling it has no or negligible negative consequences.

Additionally, I made good experience with switching the garbage collector from "ParallelGC" (the default) to G1. If you're willing to trade a bit more CPU usage for more aggressive memory cleaning, perhaps give this a try. You can pass it via environment variable:

```env
JAVA_OPTIONS="-XX:+UseG1GC -XX:+UseStringDeduplication -XX:MaxGCPauseMillis=250 -XX:MaxRAMPercentage=90.0"
```

For reference, this is the default:

https://github.com/DependencyTrack/dependency-track/blob/a6de47b920ecc4bd86d27666bdf85b67782e4263/src/main/docker/Dockerfile#L19

**Comment by nscuro** [comment]
Also note that DT per default is allowed to consume up to 90% of the available RAM (`-XX:MaxRAMPercentage=90.0`). If you do not set any resource limits, DT will take what it can. Chances are your workload doesn't even require 30GB of RAM, but because it's available it's getting used. I'd recommend to either:

* Set a memory limit in your k8s deployment
* Set a static upper limit via JVM argument, e.g.: `-Xmx16g`

Potentially, you can / should do both.

Another problem is that k8s may decide to "take away" RAM resources from the DT pod, which can cause crashes as a consequence. In contrast to CPU, memory usage is not throttle-able. So best set a limit to help k8s in scheduling the pod.

**Comment by cryptator** [comment]
Thanks for the quick response! I've set `ALPINE_DATANUCLEUS_CACHE_LEVEL2_TYPE=none` and `JAVA_OPTIONS="-XX:+UseG1GC -XX:+UseStringDeduplication -XX:MaxGCPauseMillis=250 -XX:MaxRAMPercentage=90.0 -Xmx16g"` along with setting the limits for the container and observe that the memory usage is inline with expectations after setting these variables, closing this ticket.

**Comment by nscuro** [comment]
Thanks for reporting back @cryptator. This was a good reminder that these things really should be part of our documentation. I'll get this added. Cheers!
