### ISSUE TITLE
Dependency-Track requires a minimum of 2 CPU cores

### ISSUE THREAD

**Issue by feliceg77** [DependencyTrack/dependency-track#333]
Why does Dependency-Track require a minimum of 2 CPU cores?

is it possibile delete this requirement?

**Comment by stevespringett** [comment]
DT is designed to ingest thousands of SBOMs daily, process them, and identify various forms of risk (known vulns, outdated, etc) as well as notify (email, slack, webhooks, etc). DT is designed to process all tasks asynchronously and will use all available CPU cores in order to be performant.

You can, of course, use only one CPU core, but do not expect a good experience, especially in production. 

You can disable the requirements check by removing the following line from web.xml:
```xml
<listener>
    <listener-class>org.dependencytrack.RequirementsVerifier</listener-class>
</listener>
```

**Comment by feliceg77** [comment]
I don't want use one cpu, but i have an error at start of dtrack when i deploy it on mesos. CPU requirements doesn't start dtrack with latest version of java 8 (202).

**Comment by stevespringett** [comment]
You could always pass in `-XX:ActiveProcessorCount=<count>` in JAVA_OPTIONS. This will tell the JVM how many processors you have in the event it's not being correctly determined by the JVM
