### ISSUE TITLE
Dependency Check Support

### ISSUE THREAD

**Issue by jaskaransinghdr6j** [DependencyTrack/dependency-track#354]
Hey Steve,

We've been using Dependency Track 3.4.0 for a while now, and have recently been getting inconsitent errors while importing Dependency check reports.

The API posting the scans is successful, the project is created in Dependency Track (PROJECT table entry present), but the Project has "No Data Available" and no dependencies are associated with the project as well. The SCAN table also does not create an entry for the project and it's associated uploaded scan.

Current Setup:
Dependency Track : 3.4.0
Dependency Chck : 5.0.0M2

I have not noticed the same in Dependency Check v4, hence would like to know if Dependency Check v5 reports will be supported in 3.4.1 or 3.4.5 or in future so we can plan accordingly. We have a service based Dependency Check implementation which offloads scanning to our servers instead of Jenkins/Dev machines, due to large volume, and scans are then posted to Dependency Track for aggregation and notifications. 

Keep up the good work!

**Comment by stevespringett** [comment]
Importing Dependency-Check scans is not recommended. It can be done, but the result will not be great. See: https://docs.dependencytrack.org/best-practices/

Dependency-Check 5 introduces a new XML schema which Dependency-Track does not support. Last I checked, the timestamp in the XML report was either in a different format than before, or was missing, and the XSD only specified it as being a string, so its hard to know what the specific issue is. But the v2 XSD is incompatible with the 1.x XSD's which Dependency-Track v1 - v4 used. 

In Dependency-Track v3.5, I will likely put in a check for the Dependency-Check XML version and abort with warning (log) if schema v2 or higher is uploaded.

At the moment, importing ODC5 is a very low priority since it's not a best practice and there is a backlog of risk identification and reduction enhancements that the community is waiting for.
