### ISSUE TITLE
Java 11 Support

### ISSUE THREAD

**Issue by Zyggyrat** [DependencyTrack/dependency-track#376]
I see from #175 that Java 11 Support was planned for a Q4 2018 release. Has that been accomplished and released?

Having downloaded the .war today, upon running it I get the following error:
```
15:18:06.699 INFO [Config] --------------------------------------------------------------------------------
15:18:06.700 INFO [Config] Initializing Configuration
15:18:06.702 INFO [Config] System property alpine.application.properties not specified
15:18:06.702 INFO [Config] Loading application.properties from classpath
15:18:06.706 INFO [Config] --------------------------------------------------------------------------------
15:18:06.707 INFO [Config] Application: Dependency-Track
15:18:06.708 INFO [Config] Version:     3.5.0
15:18:06.709 INFO [Config] Built-on:    2019-06-07T06:11:28Z
15:18:06.709 INFO [Config] --------------------------------------------------------------------------------
15:18:06.710 INFO [Config] Framework:   Alpine
15:18:06.710 INFO [Config] Version :    1.5.0
15:18:06.710 INFO [Config] Built-on:    2019-06-07T03:50:32Z
15:18:06.710 INFO [Config] --------------------------------------------------------------------------------
15:18:06.740 INFO [RequirementsVerifier] Initializing requirements verifier
15:18:06.740 ERROR [RequirementsVerifier] Using Java version: 11.0.0
15:18:06.741 ERROR [RequirementsVerifier] Dependency-Track requires Java 8 with a minimum update of 162 or higher. Cannot continue.
```

Please advise.

Thanks,
zyggyrat

**Comment by stevespringett** [comment]
Java 9 and higher are not currently supported

**Comment by stevespringett** [comment]
BTW, I'm still waiting for some dependencies and Maven build plugins to support anything higher than Java 8. At the time being, I'm simply not capable of compiling for Java 11.

Likely what will happen is that I'll try to figure out JPMS for the 10th or so time - I've wasted so much time on this no thanks to Oracle. And I'll attempt to get it working with the classpath rather than the modulepath. I've tried previously and it didn't work. If I can get it to still compile with Java 8 and run on Java 11, that would be the best I can do for now until all dependencies and build plugins support Java 11.

There hasn't been a big incentive to do so until recently, since there has been a lot of backports from Java 10 and Java 11 to Java 8, especially around Docker support.

If anyone has the capacity to investigate this, it would be really helpful.

**Comment by Zyggyrat** [comment]
This is something I could look at but probably not until August. If no one's had a chance to tackle this by then, I'd be happy to take a look. I've gotten done Java 8 to 11 conversions before, but tooling has been an issue (especially as I was doubly affected by Oracle as a NetBeans user and our projects have relied on some of the Java EE features that have taken longer to get on the Apache variant).

**Comment by stevespringett** [comment]
I've been doing some testing and it appears that Java 11 may be substantially slower than Java 8. I still need to do more testing, but so far, I am not impressed.

**Comment by stevespringett** [comment]
The Docker image has been changed back to Java 8 after substantial testing demonstrated Java 11 performance problems. However, Dependency-Track v3.6 will not prevent use of Java 11.
