### ISSUE TITLE
How matching manually created vulnerabilities with components works?

### ISSUE THREAD

**Issue by pachulo** [DependencyTrack/dependency-track#419]
We're trying Dependency Check feature to manually add vulnerabilities, but reading the documentation:
https://docs.dependencytrack.org/usage/private-vuln-repo/

We are not really sure how we should create them to match certain components (maven artifacts in our particular example). I guess we should use the «Vulnerable Versions» box:
![image](https://user-images.githubusercontent.com/3256953/63420157-6bdcef80-c406-11e9-9ba6-1354cf625831.png)
But we are not really sure which information we need there...do we have to create a CPE? Or maybe a Package URL?

**Comment by stevespringett** [comment]
It's a preview feature and not feature complete. The work that is going into 3.6.0 which is removing the embedded Dependency-Check instance and replacing it with an internal CPE Analyzer, is actually required for Internal vulnerabilities to be able to have an effect on components within the affected range. This feature will likely not be complete in 3.6.0, but the foundational pieces to complete it will be in place.

**Comment by stevespringett** [comment]
And yes, the idea would be able to support both CPE and PURL.

**Comment by stevespringett** [comment]
In v3.6 there is a VulnerableSoftware object which describes the
* CPE (v2.2 and v2.3)
* Individual CPE parts (vendor, product, version, edition, etc)
* PURL
* Individual PURL parts (namespace, name, version, etc)
* versionEndExcluding
* versionEndIncluding
* versionStartExcluding
* versionStartIncluding

This will be used to perform precise analysis of NVD and VulnDB data when components have a CPE such as:
* `cpe:/o:linux:linux_kernel:4.4.6`
* `cpe:2.3:o:linux:linux_kernel:4.4.6:*:*:*:*:*:*:*`
and there's a matching CPE in a VulnerableSoftware object or if the VulnerableSoftware object describes something like:
* `cpe:2.3:o:linux:linux_kernel:*:*:*:*:*:*:*:*`
  * versionEndExcluding = 5.0.0

This is how precise NVD/VulnDB matching will be performed behind the scenes. There are about 2.2 million VulnerableSoftware objects which are automatically created in v3.6 from data from the NVD. So anytime you add a component with a valid CPE, you'll be able to automatically identify if that component has any known vulnerabilities. It's pretty slick.

An analyzer for PURL is also planned. The NVD doesn't use PURL, but the internal vulnerability database will. So in 3.7, the plan is to finalize the internal vulnerability editing feature so that it would be possible to not only create new VulnerableSoftware definitions, but those definitions could also contain PURL fragments such as:
* `pkg:npm/express@4.17`
* `pkg:npm/express`
  * versionEndExcluding = 4.18

So basically, the VulnerableSoftware definition will describe a CPE or PURL with either an exact version or a version range. Whenever a component is added or analyzed, it will be analyzed against all VulnerableSoftware definitions. All of this logic is in addition to the existing OSS Index and NPM Audit analyzers.

**Comment by msymons** [comment]
@stevespringett, just to check,...  the mechansm will allow for multiple ranges?  ie, where the internal vulnerability is similar to [CVE-2019-7614](https://nvd.nist.gov/vuln/detail/CVE-2019-7614)

> versions before 7.2.1 and 6.8.2

**Comment by stevespringett** [comment]
Thats correct. It requires two VulnerableSoftware objects in this case, one for each range. Very similar to how the NVD works in this case.

**Comment by stevespringett** [comment]
I'm closing out this ticket. Note that I put #96 on the roadmap for v3.7. Much of the foundational work to get this working is being shipped in v3.6, and v3.7 will add the ability to use the same framework for internally reported vulnerabilities as well.
