### ISSUE TITLE
Dependency-Track shows 0 vulnerabilites 

### ISSUE THREAD

**Issue by shounakitraj** [DependencyTrack/dependency-track#421]
Hi Steve,

I am using Jenkins plugin of Dependency-Track to upload data to Dependency Track. Following are the version details:

Dependency-Track: v3.5.1
Jenkins DT Plugin: 2.1.0
Jenkins DC Plugin: 5.0.2

I am trying to scan .net project using both Dependency Check and Dependency Track. 
I am using cyclonedx to generate BOM of DotNet .sln file and uploading it to Dependency Track and I am also publishing DC results after build completion.

So my observation is, DC shows multiple vulnerabilities on Jenkins Server, but when the BOM of same project is uploaded to DT it shows 0 vulnerabilities even though there are multiple components with known vulnerabilities are listed on 'Components' Page of DT.

Can you help me, if I am doing anything wrong.

Thanks

**Comment by stevespringett** [comment]
https://docs.dependencytrack.org/odt-odc-comparison/

In DT, ensure that the embedded Dependency-Check scanner is disabled and that OSS Index is enabled.

https://docs.dependencytrack.org/best-practices/

With best practices implemented, it's very uncommon for DT to have false positives, whereas DC will likely always have false positives. If you're doing a comparison, you'll need to remove all of the noise from the DC report before comparing.

When the embedded DC scanner is disabled and OSS Index scanner is enabled, comparing DT to a commercial vendor (that does manifest analysis) would be a much more relevant comparison.

**Comment by shounakitraj** [comment]
Hi Steve,

Thanks a lot for the quick and detailed response. I did following things:

Disable Dependency-Check Configuration
Enabled Sonatype OSS Index Configuration

Tried scanning again, my observation is it gathers all the data using cyclonedx genearated BOM, still it displays the list of vulns as 0.

But if I check the component list, there are few libraries which are old and are vulnerable with public CVEs. For Example, the component list has JQuery 1.9.1 which is vulnerable to XSS and Prototype Pollution (https://snyk.io/test/npm/jquery/1.9.1), still in DT it is marked as non-vulnerable.

Following is the screenshot
![image](https://user-images.githubusercontent.com/25792555/63569233-2ea76780-c596-11e9-9573-8a9492d14414.png)

Could you please check and let me know if I am missing something.

Thanks,

**Comment by stevespringett** [comment]
Ensure your components have valid package urls. For example, jQuery should have a Package URL of `pkg:npm/jquery@1.9.1`. I'm not sure how it got a mixed-case name either. It should be all lower case. Very strange. I assume you created CycloneDX BOM for the Javascript components using the Node module?

**Comment by stevespringett** [comment]
If OSS Index is enabled and you have a valid Package URL for the first component for example, you should be seeing 4 vulns for that component according to OSS Index: https://ossindex.sonatype.org/component/pkg:npm/jquery@1.9.1

**Comment by shounakitraj** [comment]
Looks like it took some time to generate report, but now I am able to see 4 vulns for JQuery 1.9.1 and Jquery 1.12.4

Attached screenshot

![image](https://user-images.githubusercontent.com/25792555/63571359-97461280-c59d-11e9-86d1-976d8b24cd80.png)

Thanks a lot for help, DT has minimized lots of FPs/noise that is present in DC report.

Thanks again :)

**Comment by stevespringett** [comment]
Fantastic. Glad its working

**Comment by msymons** [comment]
JQuery is an example of a component where OSS Index was not originally processing the component correctly due to case-sensitivity.  They fixed it after I reported it [here](https://github.com/OSSIndex/vulns/issues/22)

As you can see from this, Primefaces is also now linked to CVE-2019-11358 in OSS Index... so my instance of Dependency-Track 3.5.1 is now generating all the warnings that I expect to see!

@shounakitraj, my observation is Dependency-Track will update an individual project's threat information withiin a few seconds when a BOM is uploaded.  Projects that share the same vulnerable purl(s) are also updated at the same time.  However,  if there are projects that use different versions of a vulnerable component **and** these projects do not have a BOM uploaded for a while, then DT will lag in reporting that these projects have vulnerable dependencies.   This is where the "Projects" page in DT is useful...  simply sort by "Last BOM Import" column and check that no project is out-of-date.

**Comment by shounakitraj** [comment]
@msymons, it took around 5-10 minutes to update on DT dashboard. sure I will check by sorting by 'Last BOM Import', Thanks a lot for information provided.
