### ISSUE TITLE
Policy Violations broken when using the v2 processing

### ISSUE THREAD

**Issue by malice00** [DependencyTrack/dependency-track#4215]
### Current Behavior

I've been doing some testing before upgrading to the new release and found that the policy violations are broken. I returned to v4.11.7 and turned on the v2 processing. It seems that when using this, policy violations are all over the place!

For testing purposes, I created 2 policies: 'has license' and 'no license'. When using the default processing in 4.11.7, my imported SBOM, containing 193 components, has 193 policy violations. When turning on v2 (or updating to 4.12.0), the numbers are all over the place!
In my tests, I constantly created a new project, but imported the same SBOM. The results vary from 227 to 291 policy violations. It seems almost random, but so far every new test gives me different numbers!
Re-uploading the SBOM in the same project, does not change the numbers.

### Steps to Reproduce

1. Setup DT with a 4.11.x version, v2 processing disabled
2. Create 2 policies (license is unresolved & license is not unresolved)
3. Create project and import SBOM
4. Wait for processing to finish, the nactivate v2 processing
5. Create another project and import the same SBOM
6. Wait for processing to finish and compare the results of the policy violations

### Expected Behavior

I would expect the number of policy violations to be consistently the same between imports of the same SBOM.

### Dependency-Track Version

4.11.x

### Dependency-Track Distribution

Executable WAR

### Database Server

H2

### Browser

Mozilla Firefox

### Checklist

- [x] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [x] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this defect was already reported

**Comment by nscuro** [comment]
Thanks for reporting. I could reproduce the symptom, but the cause is a slightly different one.

What is happening is that policy evaluation happens *twice* after a BOM upload:

1. Once after repository metadata analysis completes
2. And again after vulnerability analysis completes

https://github.com/DependencyTrack/dependency-track/blob/6f7c49c0f2f163895b95e5b80554a49a3ec500f8/src/main/java/org/dependencytrack/tasks/BomUploadProcessingTask.java#L760-L777

Reason being that both analyses run concurrently, but policies might rely on data from both of them. If policies rely on repository metadata, only evaluating them after vulnerability analysis could result in missed violations.

The problem is that there's currently no locking at the project level for policy evaluation. Meaning evaluation of the same project can happen concurrently, which can lead to duplicate violations to be created. This is where the varying number of violations stems from.

This appears to have always been a problem, but BOM processing V2 makes it more likely to surface because it kicks off repository metadata and vulnerability analysis at the same time (i.e. upon successful processing of the BOM), whereas V1 started them gradually *during* the processing. That behavior change is due to V2 making BOM processing atomic (i.e. performing analysis is pointless if the whole BOM import might be rolled back due to an error).

To address this issue, we will:

* Introduce locking to prevent concurrent policy evaluation of the same project
* Tweak evaluation logic to ensure that existing duplicate violations will be cleaned up

**Comment by malice00** [comment]
@nscuro Looks good, thanks! 1 question though: Is it possible to get rid of the duplicates from my current projects without completely deleting them? And without losing any auditing data that might already be there?

**Comment by nscuro** [comment]
@malice00 The duplicates represent an invalid invalid application state and can not be kept around. In future versions we'll add a `UNIQUE` constraint to the database table to *definitely* prevent them.

What I can do is adding logic to prefer keeping the violation with a / the most recent analysis during de-duplication. Would that help?

**Comment by nscuro** [comment]
@malice00 How does this look? https://github.com/DependencyTrack/dependency-track/pull/4231/files#diff-46ef3bc3b3f5a71027da7ff6830a6dde811d0acaad4c937cf4e7e8df6bb210f8R193-R237

**Comment by malice00** [comment]
@nscuro That seems to have done the trick! Thanks!
