### ISSUE TITLE
Sonatype OSSIndex is returning 302

### ISSUE THREAD

**Issue by johnjebaraj** [DependencyTrack/dependency-track#473]
Tried the same url in Sonatype OSSIndex, it works fine. 

13:51:56.840 INFO [OssIndexAnalysisTask] Starting Sonatype OSS Index analysis task
13:51:57.088 WARN [OssIndexAnalysisTask] Received unexpected HTTP response 302 Moved Temporarily

 Dependency-Track v3.5.1

Build ID: eca73596-dd90-495f-9c13-931c8dab7bc0

Built On: 17 Jul 2019 at 19:11:54

**Comment by stevespringett** [comment]
This is not a defect with Dependency-Track. Sonatype appeared to have made changes to ossindex.net, which was the original domain and the domain that Dependency-Track v3.5.1 and previous use. It doesn't seem like Sonatype sent notices to registered users before the change. Like you, I just happened to notice one day, a few days prior to the release of v3.6.0.

There are two options:
1) Open an issue with Sonatype so that ossindex.net continues to work correctly
2) Upgrade to Dependency-Track v3.6.0 or higher (v3.6.1 is the current release)

Refer to https://docs.dependencytrack.org/changelog/

**Comment by johnjebaraj** [comment]
Thanks Steve. v3.6.1 is working fine. Is it possible not to hard code the base URL? also do you have plans to support github repository in near future?

**Comment by stevespringett** [comment]
All endpoints will eventually be configurable, yes.

Follow #164 for details on configurable package repo support. Since GitHub package repos implement standard package repo protocols from Maven, npm, docker, etc, they could be configured with #164 just like any other package repo.
