### ISSUE TITLE
Add Hex Repository Support

### ISSUE THREAD

**Issue by stevespringett** [DependencyTrack/dependency-track#495]
https://hex.pm/

**Comment by stevespringett** [comment]
BEAM languages (erlang, elixir, etc) now have the ability to generate CycloneDX BOMs via https://hex.pm/packages/sbom. Adding support for Hex would round out the integration support for this ecosystem.

**Comment by voltone** [comment]
This is great! I only noticed it now, with the 3.7.0 release, so I'm upgrading my server at this very moment.

I am worried that going through the API is not going to scale very well, because it is [rate-limited](https://hexpm.docs.apiary.io/#introduction/rate-limiting). The alternative is fetching the package registry directly from the repo endpoint, but this is going to be much harder to parse in Java. Anyway, I have a large number of Hex dependencies across multiple projects on my server, I'll report back if I run into issues.

It would also be great if retired package versions were flagged, but I guess this requires generic support in the MetaAnalyzer interface first. I may have a look at that at some point.

Thanks @stevespringett !

**Comment by voltone** [comment]
Had to create a small patch to get the Hex MetaAnalyzer to actually be invoked (#550)
