### ISSUE TITLE
CycloneDX BOM Generation Issue

### ISSUE THREAD

**Issue by ParthibanSG** [DependencyTrack/dependency-track#514]
I am using dependency track BOM upload via Jenkins and observing few warnings and error. Please clarify on the below

- I am compiling a multi-module Maven project which has multiple pom.xml and similarly, bom.xml is generated for all those modules. How can i integrate all bom's as one and upload to Dependency Track?

- During Jenkins build using CycloneDX  maven goal, I am getting below statements in the console. How to rectify them

[ERROR] I/O error opening Json TOC URL, using local TOC file
[WARNING] Unable to open SPDX listed license model.  Using local file copy for SPDX listed licenses

- I could see Upload of Dependency-Check report is deprecated with 3.6.1 version, is it not possible to upload dependency check xml to  Dependency Track?

Thanks

**Comment by stevespringett** [comment]
If the Maven project is a multi-module project, you need to use the `makeAggregateBom` goal. Instructions are on https://cyclonedx.org/

Support for importing Dependency-Check reports is deprecated in 3.6 and will be removed in 3.7. It is disabled by default, but can be enabled in general settings. See also:
- https://docs.dependencytrack.org/2019/09/28/v3.6.0/
- #397 
- #396

**Comment by ParthibanSG** [comment]
Thanks @stevespringett 

How about below warning and error in Jenkins. How do I resolve them?

[ERROR] I/O error opening Json TOC URL, using local TOC file
[WARNING] Unable to open SPDX listed license model. Using local file copy for SPDX listed licenses

**Comment by stevespringett** [comment]
Not sure about the warning. It's coming from SPDX tools, not directly from the Maven plugin

https://github.com/goneall/SPDX-Tools/blob/master/src/org/spdx/rdfparser/license/ListedLicenses.java#L291

**Comment by mihai-ck** [comment]
I also face like @ParthibanSG  similar messages in the Jenkins log. A simple Jenkins job that uses a maven goal:
org.cyclonedx:cyclonedx-maven-plugin:makeAggregateBom
for a maven multi-module project. 

[INFO] --- cyclonedx-maven-plugin:1.5.1:makeAggregateBom (default-cli) @ parent ---
[ERROR] I/O error opening Json TOC URL, using local TOC file
[WARNING] Unable to open SPDX listed license model.  Using local file copy for SPDX listed licenses

The scope is just to obtain the bom.xml so then after to manually load it into Dependency-Track using his web interface.
In this Jenkins job configuration is only invoked this maven goal, so is not used in the job any plugin like dependency-check or dependency-track.

The bom.xml is generated , but it is interesting how it relates with SPDX because I do not have any specific SPDX plugin or tool installed, and I only have installed 'OWASP Dependency-Check Plugin' and 'OWASP Dependency-Track Plugin'.

Do the DC and DT trigger any SPDX check or operation ?

**Comment by mihai-ck** [comment]
(small update)

I don't know how it can relate with the previous messages in the log:

[ERROR] I/O error opening Json TOC URL, using local TOC file
[WARNING] Unable to open SPDX listed license model. Using local file copy for SPDX listed licenses

but , after I have set the proper --nexus argument by having a defined the resource ending in  /.../nexus/service/rest' (for our instance) and not ending in /...../service/local/' and also after I have installed the .Net core libraries in the debian container, I no longer receive the previous error and warning.
Now the BOM is published to dependency-track instance, and the Jenkins dependency-check report is generated but something still missing from the setup to have the vulnerabilities appear in dependency-track Audit tab.

**Comment by stevespringett** [comment]
Ensure OSS Index is enabled. Use your registered email address as the API username and the token they provided you.

https://docs.dependencytrack.org/datasources/ossindex/

**Comment by mihai-ck** [comment]
For OSS Index, in the falling setup, I have set it up as suggested, and for me didn't solve the issue.
Maybe one important aspect is that the docker container was hosted under a CentOS host not in the company domain's but still in the company's network and using a proxy setup.
Now, the docker container is under a VM with CentOS but this time also hosted on a physical host with Windows 10 and inside the company's domain; so now the corporate network services are solved by the authenticated Windows 10 (with a domain user) and pass to the container (so no longer needed explicit proxy definitions).
I had a lot of different issues and with different software, that failed because of this need to explicit define the proxy to reach internet. 
Now the OSS Index is fetched in DT and I can see the info in Audit tab/section.

**Comment by stevespringett** [comment]
Ok good. Glad it's working. For reference, proxy's can be configured using the instructions here: https://docs.dependencytrack.org/getting-started/configuration/

This also relates to #265 which will include a 'test' button for each external connection type. Should make things a bit easier to test.
