### ISSUE TITLE
Version mismatch between submitted artifact and reported vulnerability

### ISSUE THREAD

**Issue by VelvetDash** [DependencyTrack/dependency-track#549]
Artifact details:
group: org.apache.activemq
artifactid: activemq-all
version: 5.15.10

this artifact generated 5 vulnerabilities:
CVE-2016-6810, CVE-2016-3088, CVE-2019-0222, CVE-2018-8006, CVE-2018-11775

However these cve only cover versions lower than 5.15.10

artifact is also not shown to be vulnerable according to search.sonartype.org
https://search.maven.org/artifact/org.apache.activemq/activemq-all/5.15.10/jar

please help to resolve. thanks.

**Comment by stevespringett** [comment]
Sonatype OSS Index does not report this version as vulnerable.
https://ossindex.sonatype.org/component/pkg:maven/org.apache.activemq/activemq-all@5.15.10

Considering that Dependency-Track relies exclusively on OSS Index for analysis of Maven artifacts, I don't know where these vulnerabilities came from. If you've upgraded from previous versions of Dependency-Track and had the embedded Dependency-Check analyzer enabled, that could explain why these false positives exist. The embedded Dependency-Check analyzer was removed in a previous release.

It's also possible that OSS Index had that version listed as vulnerable when Dependency-Track picked it up. If so, it's since been corrected.

in either case, I'd recommend globally suppressing the issue so that it doesn't affect any project that uses these components.

**Comment by VelvetDash** [comment]
issue suppressed. thanks.
