### ISSUE TITLE
No vulnerabilities in Audit 

### ISSUE THREAD

**Issue by cigoff** [DependencyTrack/dependency-track#551]
Hi,
I have installed Dtrack and created a Bom using maven for webgoat legacy to build a BOM, when I upload the bom in dtrack, no vulnerabilities are shown in audit, I have signed up for OSSindex and included the user and API key

**Comment by stevespringett** [comment]
Ensure that you're using the email address as the API username, and supply the API token they provided.

**Comment by cigoff** [comment]
Hi Steve, thank you very much. It is working as expected. 
It is observed that, the DT is not working with "nist" database. Could you please suggest on that?

**Comment by stevespringett** [comment]
> the DT is not working with "nist" database

Have you tried?

The NVD relies on CPE to describe the vendor, product, and version. If you have a BOM that contains a component with a valid CPE, then yes, the internal NVD source will be used. Most BOMs from build systems however, will not contain CPEs since CPEs are a central authority and often do not reflect the reality of how components are named.

In short, dependency managers from build systems will produce Package URLs (PURL). All official CycloneDX implementations should have PURLs for every component. 

CPEs are used for assets (that's what they were originally designed for). So if you have a BOM containing an application, operating system, or hardware device components with a CPE, then the internal analyzer will be used.

Refer to https://docs.dependencytrack.org/analysis-types/known-vulnerabilities/

**Comment by cigoff** [comment]
Yes Steve. We tried with the same bom.xml, which is already worked with "sonatype oss index". Anyway, will try with another bom as per your advice.

Thank you for quick reply.
