### ISSUE TITLE
Dashboard shows no data forever

### ISSUE THREAD

**Issue by sergioasantiago** [DependencyTrack/dependency-track#552]
The defect may already be reported! Please search for the defect before creating one.

### Current Behavior:
The main dashboard shows not data in all sections:
![image](https://user-images.githubusercontent.com/875058/71361438-466a1900-2593-11ea-98f8-d58404fa43b0.png)

### Steps to Reproduce:
Unfortunately I  can't confirm the exact reason that leads to this issue.
Extra information in Additional Details section

### Expected Behavior:
Dashboard shows summary report for all the services

### Environment:
  
  - Dependency-Track Version: 3.7
  - Distribution: [ Docker | Executable WAR | Traditional WAR ] Docker
  - BOM Format & Version: CycloneDX
  - Database Server: [ H2 | MSSQL | MySQL | PostgreSQL ] Postgresql
  - Browser: Any

### Additional Details:

(e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)
Some information:
- We have around 15K projects and growing.
- We create on new release on each new deploy in our environment
- We had an issue before with resources (low memory and CPU). Adjusted and the issue still happening.
- We have added [this parameter](https://github.com/DependencyTrack/dependency-track/issues/273#issuecomment-502925571) to our call
- So far there are no errors in logs.

**Comment by stevespringett** [comment]
The recommended resources are documented here: https://docs.dependencytrack.org/getting-started/deploy-docker/

Have you tried setting the environment variable `LOGGING_LEVEL` to `DEBUG`?

**Comment by sergioasantiago** [comment]
I've adjusted to this suggested setup one week ago. But the issue still the same.

Here is a screenshoot that shows the container resources usage.
![image](https://user-images.githubusercontent.com/875058/71575050-b7598580-2aeb-11ea-8e2d-0d24361f99fc.png)

The memory consumption increases indefinitely until the container get killed by k8s with OOM.

**Comment by stevespringett** [comment]
That looks normal and is to be expected for a container with a 16GB limit. By default, the JVM will use 90% of RAM allocated to the container. So it should max out at 14,745.6 bytes, but the current and max on the graph are both a bit over 15K. Not sure if that's a difference between 1024 vs 1000, or if there's something else in play.

One thing to note however is that the container expects 16GB to be allocated to it. If the host OS cannot provide it (because it's running too many other containers itself, etc), then you can expect the container to be killed. This is normal behavior of the Docker daemon So ensure the host can actually provide the full 16GB of RAM to it given that it may be running other things.

**Comment by stevespringett** [comment]
On another note, for large deployments, metrics seem to be an issue. Long term, metrics will be broken out into its own service (not exactly a microservice, but a domain-specific service). This will help distribute the work and reduce the load on the main DT server. Short-term, I'll see if there's some performance improvements that can be added to v3.8 along with some additional logging to help in debugging these sorts of issues.

**Comment by stevespringett** [comment]
These changes exist in the master branch and have been back-ported to the 3.7.x branch

**Comment by stevespringett** [comment]
I added a ton of debug logging and fixed two issues.

1. During a portfolio update when global component metrics were being calculated, the wrong QueryManager instance was used which would likely cause unpredictable behavior (portfolio metrics not completing, component metrics not being updated, etc)
2. Portfolio metrics are scheduled to occur every hour. They can also be triggered to occur from the UI or API. This is a resource intensive task and may take a while to complete for large installations. An hour simply may not be enough time for it to complete. So, logic was added to prevent simultaneous portfolio metric updates from executing. 

These changes exist in the master branch and have been back-ported to the 3.7.x branch

**Comment by stevespringett** [comment]
Due to the way the metrics work (and are called), I cannot realistically achieve any performance improvements without introducing additional defects. But I think the one or two issues that have been fixed along with additional logging should either 1) fix the issue, or 2) help identify where the issues is. 

I cannot reproduce, so it's hard to tell. I'll likely release 3.7.1 shortly with these fixes.

**Comment by stevespringett** [comment]
Also, question. with 15K projects, how many components do you have?

**Comment by sergioasantiago** [comment]
The UI says we have about ~11200 components.
We use the api to upload the CycloneDX bom file.
The project is the service name, and we create a new version on every new release created in our CI/CD.

Question: Is there any task that I can run to inactivate old releases in bucket? With that I guess we can improve a lot the performance, because in our use case, we can inactivate projects that has no update since X days ago.

**Comment by stevespringett** [comment]
Thank you. If you have only a single version of a service deployed at any given time, then deleting the old projects would be ideal. There's no sense of tracking vulnerabilities for projects that are not deployed and therefore do not represent any risk to the org. If you only have a single version of a service deployed, then I would highly recommend keeping a single project. That way you can have trending information to determine if risk is increasing/decreasing over time.

If you have multiple versions of a service in production, there should be a way to delete projects from DT when an old version of a service is decomiossioned and no longer deployed. You may be able to use project tags or project properties and correlate those to an internal system which tracks deployments. Then have a daily process to cleanup everything no longer deployed.

**Comment by sergioasantiago** [comment]
I changed how we map the project+version. It should decrease significantly the amount of projects.
Let's see how DT will behave next days, and as soon as you release the new version with those fixes that you mentioned I will upgrade as well.
Thanks!

**Comment by sergioasantiago** [comment]
I have decrease the number of services from 15K to almost 500. I used the API projects/DELETE to remove the obsolete projects. Even though it seems the dashboard still no able to refresh.
Is there anything else that I need to nuke? I thought about complete nuke the DT DB, but I don't want to lost the information about users and vulnerability data base.
Any advice on that?

**Comment by sergioasantiago** [comment]
UPDATE: After ~4 hours, the dashboard is shown again. Looks like deleting the projects solve the issue.

**Comment by stevespringett** [comment]
Ok, so if the update took 4 hours and portfolio updates are scheduled to occur every hour, then that could introduce a scenario where metrics will never complete, and would essentially start creating a traffic jam of sorts what would progressively get worse over time.

This scenario will be addressed in 3.7.1. I'll try to push it out later tonight (my time) so that you'll have a new version available first thing if the morning.

**Comment by stevespringett** [comment]
v3.7.1 is now available. Closing ticket. If you continue to experience issues, turn on debug logging as it should greatly assist in diagnosing other potential issues.
