### ISSUE TITLE
Reason for continuous increase of memory usage

### ISSUE THREAD

**Issue by Bnjmn83** [DependencyTrack/dependency-track#623]
DTrack's memory usage in our Postgres DB increases every day by ~100 MB.
What can be the reason for this? We did not add any new projects recently.

**Comment by stevespringett** [comment]
Not sure if you're referring to runtime memory of the DT server or the storage of the DT database.

DT will use whatever memory the JVM allocates to it. If the max heap is set to 8G for example, then DT will use up to 8GB.. However, if initially it doesn't need it, maybe only needs 4GB one day, but the next day needs 4.5GB due to additional demands on the server, the JVM will have blocked off 4.5GB and will not free it up. The memory has been allocated up to the max heap size. Refer to the Oracle JVM docs on how heap (and garbage collection) works for additional details.

If you're referring to the size of the database. That really depends on the number of components, the number of projects, and how many times the metrics change, as all of the historical metrics are tracked so that reporting can be performed.

**Comment by Bnjmn83** [comment]
I am referring to the ladder, the size of the database. Are there any parameters to tweak this behavior or do I have to live with this growth rate and acquire more space?

**Comment by stevespringett** [comment]
Aa projects change components or component versions over time and since the system keep historical metrics so users can evaluate risk over time, the database storage needs will increase over time.
