### ISSUE TITLE
Enable OSS Index by default

### ISSUE THREAD

**Issue by stevespringett** [DependencyTrack/dependency-track#636]

**Comment by ssimd** [comment]
Hi,
just wondering if that is a good idea - since I am not even sure that we can use the Sonatype OSS Index at our company just like this...
Looking at their ToS, one could understand that the use in DependencyTrack is not permitted:

https://ossindex.sonatype.org/tos

i.e.:

> 3. Right to Use the Materials
> Subject to your compliance with the terms and conditions of this Agreement, you may access and use the Materials solely for your **personal, internal use**. 

--> otherwise I need to first contact them via email and hope for their agreement.

Also:

> 7. Rules of Conduct
> In accessing or using the Website, you may not: 
> ...
> Systematically download and store any or all of the Website’s content.
> ...

So, this sounds to me like this:
* if I am a company, I need to ask them first
* if I am a person, I still can't use DT because it would violate the rules of conduct

I am not a lawyer, but just reading this makes me doubt that it should be enabled by default.

IMO it should be clearly stated in DT before enabling the OSS Index that you need to accept their ToS and that you might need to ask their permission via email first.

However, I will write them an email to ask for our intended use, because their ToS are rather not suggested this use is allowed out of the box.

**Comment by stevespringett** [comment]
I've been chatting with Brian Fox as well as Justin Young and Najla Damand (dedicated OSS Index product manager) about enabling OSS Index by default in DT. 

We have agreed upon what is required on both ends to do so are are moving forward. Feel free to reach out to Sonatype regarding the TOS. I think that's a good catch as it likely needs to be updated.

**Comment by ssimd** [comment]
Alright, will do! If they are open to the usage in DT, esp. by default, the ToS should not create doubt in that.

Thank you for your quick reply and really great work on this and related projects. It's a tremendous help for us.

**Comment by stevespringett** [comment]
335e5acb3de80adf763e52dc61b2824d1b99c7c0

**Comment by sephiroth-j** [comment]
Can we also activate OSS Indexer now in version 3.8 without having an account too?

**Comment by stevespringett** [comment]
No. 3.8 and lower still requires an account.

**Comment by stevespringett** [comment]
Closing. Anonymous OSS Index enabled by default in v4.0 - to be released soon.
