### ISSUE TITLE
Exclude a library from bom

### ISSUE THREAD

**Issue by EvgeniaPatsoni** [DependencyTrack/dependency-track#675]
There is a library in our pom.xml that is causing an error when trying to generate a CycloneDX bom, and I was wondering if there is a way to exclude certain libraries from the bom creation process - something similar to a suppress.xml maybe? - so that they will not appear in the final bom.xml file.

**Comment by stevespringett** [comment]
That would be a question for https://github.com/CycloneDX/cyclonedx-maven-plugin/ as there is a slightly different audience that pays attention to issues regarding the implementations.

But no, there is not a way to do that. If the issue is with an invalid POM, then I'd suggest contacting the project. If there's a defect in the Maven plugin, create an issue at https://github.com/CycloneDX/cyclonedx-maven-plugin/ or submit a PR to fix any issue. Omitting dependencies however, will not be accepted.
