### ISSUE TITLE
Add support for Fortify SSC v20.1.0 and higher

### ISSUE THREAD

**Issue by akevinlee** [DependencyTrack/dependency-track#700]
As per title, 

I'm pretty sure this is because of the following from the 20.10.0 SSC release notes:

"HTTP Basic authentication was deprecated for all REST API endpoints except for /api/v1/tokens/*, /api/v1/auth/* and /api/v1/license."

A quick look at the code and it seems you are trying to call the "upload" functionality using Basic Auth not with a "FortifyToken".

"https://www.microfocus.com/documentation/fortify-software-security-center/2010/"

Regards,

Kevin
kevin.lee@microfocus.com

**Comment by stevespringett** [comment]
Yeah, 20.1 broke a lot of integrations, not just DT - My employer is also scrambling to resolve this with their own plugins as well as plugins from commercial SCA.

DT first uses basic auth to retrieve a file token
https://github.com/DependencyTrack/dependency-track/blob/master/src/main/java/org/dependencytrack/integrations/fortifyssc/FortifySscClient.java#L50

Then using the token it uploads the payload:
https://github.com/DependencyTrack/dependency-track/blob/master/src/main/java/org/dependencytrack/integrations/fortifyssc/FortifySscClient.java#L73

This is what the UI previously did. 

I would classify this as a defect in SSC as `/api/v1/fileTokens` is a versioned API and it's behaviour should not change. I think the proper way of removing basic auth would have been to create a `/api/v2/fileTokens` endpoint and communicate a deprecation strategy for the v1 API. This was not done, so many things that connect to SSC broke.

Additionally, in the 20.1 release notes it states "HTTP Basic authentication was deprecated for all REST API endpoints". IME, deprecation implies that a feature is discouraged from being used and will be removed in a future release. IME, once something is deprecated, it is rare that it also does not work. In fact, the definition of the @Deprecated annotation from Oracle states "...are discouraged from using, typically because it is dangerous, or because a better alternative exists". So someone reading the release notes will likely not understand that 20.1 has breaking changes. That was not properly communicated.

---
I'll try to resolve this in the next release of DT. I'd like to remove the custom connection code and replace it with https://github.com/fortify/ssc-restapi-client if possible.

**Comment by akevinlee** [comment]
Great thanks,

Yes, thinking about it as you describe it was certainly not good. I don’t work in Micro Focus R&D but I will certainly communicate it back.

Kevin

**Comment by Heaven4All** [comment]
Hi, , regarding this issue, there is no plan to fix ODT 3.x ?

**Comment by stevespringett** [comment]
Moving to v4.2. Deploying SSC 20.2 is giving me trouble ATM.
