### ISSUE TITLE
Single BOM for multi tech project

### ISSUE THREAD

**Issue by nagmashaikh1** [DependencyTrack/dependency-track#751]
Hello,

Currently I use cyclonedx to create a bom specification to be uploaded on dependency track. However, my [project is made of multiple tech like dotnet, angular, node, maven package.

Using cyclonedx when bm file is created only dotnet packages/dependencies are written/documented nto the bom.xml file and other packages are neglected.

Is there a tool that can create single bom.xml file which would include all dependencies irrespective of technology specific cyclonedx tool so that I don't have to create multple bom.xml for one project and that is also compatible to work with dependency track?

Thanks

**Comment by stevespringett** [comment]
The CycloneDX NPM module can merge boms together using the `--append` option.
See: https://github.com/CycloneDX/cyclonedx-node-module

Related to #571

**Comment by nagmashaikh1** [comment]
Hello,

Thanks steve. Yes that worked.
But this requires me to install dotnet cyclonedx, cyclonedx for node and cyclonedx implementation retire and then combine all the bom.xml file into one.
Is there any other utility that can just generate one bom.xml in one single command rather than having to install and execute these three implementations for one project?

**Comment by stevespringett** [comment]
I'm not aware of any single tool that builds a bom across multiple ecosystems. That type of tool would be a lot of work to create, as the tool would need to have dependency resolution mechanisms for every supported ecosystem (they all resolve dependencies slightly differently), and would need to support the packaging format and repository API for each ecosystem. That would be a lot of work recreating the wheel which is one of the primary reasons why CycloneDX has native tools for each ecosystem.

Due to the simplicity of the CycloneDX model, it's possible to use standard XML tools to merge the BOMs together. There are many XML command line utilities that can perform this function.

You can take a look at [ORT](https://oss-review-toolkit.org/). It supports multiple ecosystems, but I believe the native tools need to be installed in order for them to be supported.

Also see: https://cyclonedx.org/tool-center/

Another possibility is to hold out for https://github.com/DependencyTrack/dependency-track/issues/84 to be complete, or provide a PR to make it happen. Once this ticket is complete, each ecosystem's build would have it's own project, and each individual project could optionally roll up to a parent project which would inherit all the component, metrics, and risk from child projects.

**Comment by nagmashaikh1** [comment]
Hi Steve,

Thanks for the information.
Is there a way cyclonedx can identify maven packages in dotnet project? These are added in a zip directory.

Thanks
