### ISSUE TITLE
Add pageSize and pageNumber to swagger

### ISSUE THREAD

**Issue by sergioasantiago** [DependencyTrack/dependency-track#789]
As a follow up to this closed issue https://github.com/DependencyTrack/dependency-track/issues/209
I would like to suggest an addition of the query parameters pageNumber and pageSize to swagger definition.

When using a [swagger-codegen](https://github.com/swagger-api/swagger-codegen), this parameters are missing, and there is no way to paginate the e.g: `projects` api

**Comment by stevespringett** [comment]
Currently, the swagger docs are auto generated and awful at best. Use them as a guide because the reflection support for the Java implementation is less than stellar.

The only way that I've found to accurately create swagger from complex Java systems is to manually create and maintain it - bypassing all autogenerated swagger docs.

In the future, I'll likely rip out the autogenerated swagger and replace it with an actual swagger file that is manually maintained.

**Comment by stevespringett** [comment]
Closing and incorporating these changes into #840. Please follow that ticket for updates.
