### ISSUE TITLE
Dependence Track tools does not detect known vulnerability of Spring-core:5.1.0.Release and PostgreSQL jdbc driver 42.2.1

### ISSUE THREAD

**Issue by rvsoni** [DependencyTrack/dependency-track#834]
Dependence Track tools does not detect known vulnerability of Spring-core:5.1.0.Release and PostgreSQL jdbc driver 42.2.1

Both dependency are detected by Depencendy-check maven plugin.

See test project project on https://github.com/rvsoni/dependency-test

Dependency check html report is also attached to github repo https://github.com/rvsoni/dependency-test/tree/main/target

### Current Behavior:
Dependence Track tools does not detect known vulnerability of Spring-core:5.1.0.Release and PostgreSQL jdbc driver 42.2.1

### Steps to Reproduce:
1) install 3.8.0 release
2) config sonatype oss analysis
3) upload bom https://github.com/rvsoni/dependency-test/blob/main/target/bom.xml
4) see result.

### Expected Behavior:
Dependence Track tools should detect known vulnerability of Spring-core:5.1.0.Release and PostgreSQL jdbc driver 42.2.1
same as Depencency check maven plugin report (https://github.com/rvsoni/dependency-test/blob/main/target/dependency-check-report.html)

### Environment:
  
  - Dependency-Track Version: 3.8.0
  - Distribution: Executable WAR 
  - BOM Format & Version: CycloneDX 2.1.0
  - Database Server:  H2
  - Browser: FireFox (Fedora 33 Linux)

### Additional Details:
Also it Dependency track tool does not show analysis graph on dashboard.

**Comment by stevespringett** [comment]
Why is there a comparison being made with DC and DT?  DC is designed to identify false positives, by design. DT is not.

Refer to https://docs.dependencytrack.org/FAQ/

The two Spring vulnerabilities identified by DC are false positives as the CVEs relate to vulnerabilities in Spring Security and Spring MVC, not Spring Core.

Also note that DT relies on OSS Index to identify vulnerabilities for components with Package URL. According to OSS Index, both of these components you've specified are not vulnerable.

https://ossindex.sonatype.org/component/pkg:maven/org.springframework/spring-core@5.1.0.RELEASE
https://ossindex.sonatype.org/component/pkg:maven/org.postgresql/postgresql@42.2.1

You may want to look into the Postgres issue though. This may be an actual vulnerability that is not being reported by OSS Index. Once corrected by OSS Index https://ossindex.sonatype.org/doc/report-vulnerability, the vulnerability will show up in DT.

**Comment by rvsoni** [comment]
Thanks for in info, 

closing this

Ravi
