### ISSUE TITLE
Add UI metaphors for parent/child projects and components

### ISSUE THREAD

**Issue by stevespringett** [DependencyTrack/dependency-track#84]
The datamodel and corresponding REST resources support parent/child relationships for projects and components. Currently, the UI does not have a way to express this.

This ticket is to create UI metaphors for parent/child projects and components.

**Comment by rkg-mm** [comment]
FYI, we are working on this topic and will provide a PR as proposal in next days probably

**Comment by stevespringett** [comment]
Need to revert https://github.com/DependencyTrack/frontend/pull/272 and create a better UI experience.

**Comment by rkg-mm** [comment]
@stevespringett  @nscuro 
We tried to implement this using the TreeGrid over the last days. In theory it can work, but we have no luck once we try to implement lazy loading of children, which in my opinion is definitively necessary.

The main problem is: The plugin doesn't handle a situation well, when additional data is appended to the tree. If you append data (-> child elements), the complete view resets and starts from base level again, not expanding back to the level you had opened.
Trying to manually re-open is a struggle to get the timing with events right AND you need to handle issues with scrolling etc., and have kind of a "jumping" of the table, since its for a moment collapsed again, then uncollapsing etc (especially in deeper levels you will see the table changing and jumping between states).

Any other plugins you know that could be worth a shot? Or could we stick with our version for now and if anybody has an idea to get this done better it can still be exchanged since its mainly frontend, and data is not affected?

**Comment by stevespringett** [comment]
We can always fork TreeGrid, modify it to meet our requirements, and use that. It doesn't change a whole lot, so it should not be complicate to keep synced with the upstream.

https://github.com/wenzhixin/bootstrap-table/commits/develop/src/extensions/treegrid
