### ISSUE TITLE
Exclude inactive projects from portfolio metrics

### ISSUE THREAD

**Issue by stevespringett** [DependencyTrack/dependency-track#852]
For performance and to increase risk accuracy, inactive projects should be ignored with performing and calculating portfolio metrics

**Comment by stevespringett** [comment]
Closing. Implemented in v4.0 - to be released soon.

**Comment by msymons** [comment]
This will be a useful enhancement for getting an instant overall picture of "current projects" health.  In my environment, I had a lot of inactive projects in 3.7.1 and ended up deleting them from DT...  not because they were not wanted (they were) but simply because of the impact that they were having on metrics.  It meant that "fixing" just a single project could then have a noticable percentage impact on metrics.  If nothing else, this is good for morale, as it lets the developers see a bit easier that they are making headway.

However,  those inactive projects are still important.  A decision by Management on re-activation can be impacted by the picture that DT can provide on technical debt wrt vulnerabilities, component age, presence of banned licenses, etc. 

@stevespringett, this enhancement does not close the window to future slicing & dicing of metrics, does it?
