### ISSUE TITLE
Add SARIF support

### ISSUE THREAD

**Issue by stevespringett** [DependencyTrack/dependency-track#909]
SARIF should be able to describe vulnerable components even though its' original purpose was representing source code vulnerabilities.

Recently, the Dependency-Check project implemented SARIF support with the intended use case that the resulting file would be published to GitHub (which now supports SARIF) and can process and display results directly in GitHub.

This enhancement request is to add support for generating SARIF via an API. This would dynamically generate the SARIF (via pebble), and the resulting file would be downloaded.

**Comment by stevespringett** [comment]
Refer to https://github.com/jeremylong/DependencyCheck/issues/3081

**Comment by RunFox** [comment]
Hello!
Is any updates?

**Comment by nscuro** [comment]
@RunFox Not implemented so far. But it seems like a nice "good first issue" candidate for new contributors to work on. :)

Note on implementation: The existing `/api/v1/finding/<PROJECT_UUID>` endpoint should be extended to support an `Accept: application/sarif+json` header. If that header is provided, return the findings in SARIF format. Otherwise, return findings in the existing, DT-specific JSON format.

**Comment by aravindparappil46** [comment]
Hi folks,
I have created a PR for this enhancement: #3561 
Would appreciate any feedback! (Some eyes on the `sarif.peb` would be great!)
